[network]
listen_host    = "127.0.0.1"
listen_port    = 7002
er_listen_host = "127.0.0.1"
er_listen_port = 7022

[gateway]
host = "127.0.0.1"
port = 7010

[ha]
instance_id  = 2
peer_host    = "127.0.0.1"
peer_port    = 7001
arbiter_host = "127.0.0.1"
arbiter_port = 7100

[logging]
applog_level = "info"
syslog_level = "info"
