[network]
listen_host    = "127.0.0.1"
listen_port    = 7001
er_listen_host = "127.0.0.1"
er_listen_port = 7021

[gateway]
host = "127.0.0.1"
port = 7010

[matching_engine]
host = "127.0.0.1"
port = 7020

[ha]
instance_id  = 1
arbiter_host = "127.0.0.1"
arbiter_port = 7100

[logging]
applog_level = "debug"
syslog_level = "info"
