"""C++17 header code generator for the pubsub_itc_fw DSL."""
# pylint: disable=duplicate-code,too-many-lines

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import List

from .ast import (
    ArrayType,
    DslFile,
    EnumDecl,
    Field,
    ListType,
    MessageDecl,
    PrimitiveType,
    ReferenceType,
    StringType,
)


@dataclass
class CppGenerator:
    """Generates a C++17 header from a validated DSL AST.

    The generated header contains:
      - Endian helper functions
      - ListView<T> template
      - Enum declarations with to_string and validate helpers
      - Owning structs (for encode) and View structs (for decode)
      - encoded_size, encode, decode, skip functions per message
      - max_decode_arena_bytes and max_encode_arena_bytes helpers per message
    """

    namespace: str

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def emit(self, ast: DslFile, topics: bool = False) -> str:
        """Generate and return the complete C++ header as a string."""
        lines: List[str] = []
        w = lines.append

        self._emit_header_preamble(w)
        w("#pragma once")
        w("")
        w("#include <array>")
        w("#include <cstdint>")
        w("#include <cstring>")
        w("#include <string>")
        w("#include <string_view>")
        w("")
        w("#include <pubsub_itc_fw/BumpAllocator.hpp>")
        w("")
        w(f"namespace {self.namespace} {{")
        w("")
        self._emit_endian_macros(w)
        w("")
        self._emit_endian_helpers(w)
        w("")
        self._emit_list_view(w)
        w("")

        for decl in ast.declarations:
            if isinstance(decl, EnumDecl):
                if topics and decl.name == "Topics":
                    self._emit_topics_enum_class(decl, w)
                else:
                    self._emit_enum(decl, w)
                    w("")
                    self._emit_enum_functions(decl, w)
                w("")

        for decl in ast.declarations:
            if isinstance(decl, MessageDecl):
                w(f"struct {decl.name};")
        if any(isinstance(d, MessageDecl) for d in ast.declarations):
            w("")

        enum_names = {decl.name for decl in ast.declarations if isinstance(decl, EnumDecl)}

        for decl in ast.declarations:
            if isinstance(decl, MessageDecl):
                self._emit_message_structs(decl, w, enum_names)
                w("")

        for decl in ast.declarations:
            if isinstance(decl, MessageDecl):
                self._emit_message_functions(decl, w, enum_names)
                self._emit_decode_wrapper(decl, w)
                w("")

        w(f"}} // namespace {self.namespace}")
        w("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Header preamble
    # ------------------------------------------------------------------

    def _emit_header_preamble(self, w):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        w("// -----------------------------------------------------------------------------")
        w("//  This file was automatically generated by the DSL code generator.")
        w("//  Do NOT edit this file manually.")
        w("//")
        w(f"//  Generated on: {timestamp}")
        w("// -----------------------------------------------------------------------------")
        w("")

    # ------------------------------------------------------------------
    # Endian support
    # ------------------------------------------------------------------

    def _emit_endian_macros(self, w):
        w("#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__")
        w("#  define HOST_IS_LITTLE_ENDIAN 1")
        w("#else")
        w("#  define HOST_IS_LITTLE_ENDIAN 0")
        w("#endif")

    def _emit_endian_helpers(self, w):
        w("inline void write_uint16_le(uint8_t* buffer, std::uint16_t value) {")
        w("    buffer[0] = static_cast<std::uint8_t>(value & 0xFF);")
        w("    buffer[1] = static_cast<std::uint8_t>((value >> 8) & 0xFF);")
        w("}")
        w("")
        w("inline std::uint16_t read_uint16_le(const uint8_t* buffer) {")
        w("    return static_cast<std::uint16_t>(")
        w("        (std::uint16_t(buffer[0])     ) |")
        w("        (std::uint16_t(buffer[1]) << 8));")
        w("}")
        w("")
        w("inline void write_uint32_le(uint8_t* buffer, std::uint32_t value) {")
        w("    buffer[0] = static_cast<std::uint8_t>( value        & 0xFF);")
        w("    buffer[1] = static_cast<std::uint8_t>((value >>  8) & 0xFF);")
        w("    buffer[2] = static_cast<std::uint8_t>((value >> 16) & 0xFF);")
        w("    buffer[3] = static_cast<std::uint8_t>((value >> 24) & 0xFF);")
        w("}")
        w("")
        w("inline std::uint32_t read_uint32_le(const uint8_t* buffer) {")
        w("    return (std::uint32_t(buffer[0])      ) |")
        w("           (std::uint32_t(buffer[1]) <<  8) |")
        w("           (std::uint32_t(buffer[2]) << 16) |")
        w("           (std::uint32_t(buffer[3]) << 24);")
        w("}")
        w("")
        w("inline void write_uint64_le(uint8_t* buffer, std::uint64_t value) {")
        w("    for (int i = 0; i < 8; ++i) {")
        w("        buffer[i] = static_cast<std::uint8_t>((value >> (8 * i)) & 0xFF);")
        w("    }")
        w("}")
        w("")
        w("inline std::uint64_t read_uint64_le(const uint8_t* buffer) {")
        w("    std::uint64_t value = 0;")
        w("    for (int i = 0; i < 8; ++i) {")
        w("        value |= (std::uint64_t(buffer[i]) << (8 * i));")
        w("    }")
        w("    return value;")
        w("}")

    # ------------------------------------------------------------------
    # ListView<T>
    # ------------------------------------------------------------------

    def _emit_list_view(self, w):
        w("template<typename T>")
        w("struct ListView {")
        w("    T* data = nullptr;")
        w("    std::size_t size = 0;")
        w("")
        w("    const T* begin() const { return data; }")
        w("    const T* end()   const { return data + size; }")
        w("    const T& operator[](std::size_t index) const { return data[index]; }")
        w("")
        w("    bool empty()        const { return size == 0; }")
        w("    std::size_t length() const { return size; }")
        w("};")

    # ------------------------------------------------------------------
    # Enum
    # ------------------------------------------------------------------

    def _emit_enum(self, enum: EnumDecl, w):
        w(f"enum {enum.name} : {self._cpp_int_type(enum.underlying_type)} {{")
        for index, entry in enumerate(enum.entries):
            comma = "," if index + 1 < len(enum.entries) else ""
            w(f"    {entry.name} = {entry.value}{comma}")
        w("};")
        w("")
        w(f"constexpr std::string_view to_string({enum.name} value) {{")
        w("    switch (value) {")
        for entry in enum.entries:
            w(f"    case {enum.name}::{entry.name}: return std::string_view(\"{entry.name}\");")
        w("    default: return std::string_view(\"<unknown>\");")
        w("    }")
        w("}")
        w("")
        w(f"constexpr bool validate({enum.name} value) {{")
        w("    switch (value) {")
        for entry in enum.entries:
            w(f"    case {enum.name}::{entry.name}: return true;")
        w("    default: return false;")
        w("    }")
        w("}")

    # ------------------------------------------------------------------
    # Topics enum class (framework enum pattern)
    # ------------------------------------------------------------------

    def _emit_topics_enum_class(self, enum: EnumDecl, w):
        """Emit the Topics enum as a framework enum class.

        Follows the project's enum pattern: a class containing a C-style
        Tag enum, an explicit single-argument constructor, as_tag(),
        as_string(), is_equal(), and a free operator==.
        The underlying integer type matches the DSL declaration.
        """
        cpp_type = self._cpp_int_type(enum.underlying_type)
        tag = f"{enum.name}Tag"

        w(f"class {enum.name} {{")
        w("public:")
        w(f"    enum {tag} : {cpp_type} {{")
        for entry in enum.entries:
            w(f"        {entry.name} = {entry.value},")
        w("    };")
        w("")
        w(f"    constexpr explicit {enum.name}({tag} t) : tag_(t) {{}}")
        w("")
        w(f"    [[nodiscard]] {tag} as_tag() const {{ return tag_; }}")
        w("")
        w(f"    [[nodiscard]] std::string as_string() const {{")
        w("        switch (tag_) {")
        for entry in enum.entries:
            w(f"        case {entry.name}: return \"{entry.name}\";")
        w("        default: return \"<unknown Topics: \" + std::to_string(static_cast<int>(tag_)) + \">\";")
        w("        }")
        w("    }")
        w("")
        w(f"    [[nodiscard]] bool is_equal(const {enum.name}& rhs) const {{ return tag_ == rhs.tag_; }}")
        w("")
        w("private:")
        w(f"    {tag} tag_;")
        w("};")
        w("")
        w(f"inline bool operator==(const {enum.name}& lhs, const {enum.name}& rhs) {{")
        w("    return lhs.is_equal(rhs);")
        w("}")
        w("")
        w(f"inline bool operator!=(const {enum.name}& lhs, const {enum.name}& rhs) {{")
        w("    return !lhs.is_equal(rhs);")
        w("}")

    # ------------------------------------------------------------------
    # Message structs (owning and view)
    # ------------------------------------------------------------------

    def _emit_message_structs(self, msg: MessageDecl, w, enum_names=None):
        name = msg.name

        w(f"struct {name} {{")
        for field in msg.fields:
            if field.optional:
                w(f"    bool has_{field.name} = false;")
            w(f"    {self._cpp_type_owning(field.type)} {field.name}{{}};")
        w("};")
        w("")

        w(f"struct {name}View {{")
        for field in msg.fields:
            if field.optional:
                w(f"    bool has_{field.name} = false;")
            w(f"    {self._cpp_type_view(field.type, enum_names)} {field.name}{{}};")
        w("};")

    # ------------------------------------------------------------------
    # Enum wire-format functions
    # ------------------------------------------------------------------

    def _emit_enum_functions(self, enum: EnumDecl, w):
        """Emit encoded_size, encode, and decode functions for an enum.

        Enums are encoded as their underlying integer type. This allows
        message encode/decode to call encoded_size() and encode()/decode_*()
        on enum-typed fields without any special-casing in the message paths.
        """
        name = enum.name
        cpp_type = self._cpp_int_type(enum.underlying_type)
        # Map underlying type to wire-format write/read helpers and byte width.
        wire_helpers = {
            "int8_t":  ("1", None,              None),
            "int16_t": ("2", "write_uint16_le",  "read_uint16_le"),
            "int32_t": ("4", "write_uint32_le",  "read_uint32_le"),
            "int64_t": ("8", "write_uint64_le",  "read_uint64_le"),
        }
        width, write_fn, read_fn = wire_helpers[cpp_type]

        # encoded_size
        w(f"inline constexpr std::size_t encoded_size([[maybe_unused]] {name} value) {{")
        w(f"    return {width};")
        w("}")
        w("")

        # encode
        w(f"inline bool encode({name} value, uint8_t* out_buffer, std::size_t out_size,")
        w("                    std::size_t& bytes_written, std::size_t& bytes_needed) {")
        w(f"    bytes_needed = {width};")
        w("    if (out_size < bytes_needed) { bytes_written = 0; return false; }")
        if write_fn:
            unsigned_type = "uint" + cpp_type[3:]  # int32_t -> uint32_t
            w(f"    {write_fn}(out_buffer, static_cast<std::{unsigned_type}>(value));")
        else:
            w("    *out_buffer = static_cast<std::uint8_t>(value);")
        w(f"    bytes_written = {width};")
        w("    return true;")
        w("}")
        w("")

        # decode
        w(f"inline bool decode_{name}({name}& out, const uint8_t*& read_cursor,")
        w("                           std::size_t& bytes_remaining,")
        w("                           [[maybe_unused]] pubsub_itc_fw::BumpAllocator& decode_arena,")
        w("                           [[maybe_unused]] std::size_t& arena_bytes_needed) {")
        w(f"    if (bytes_remaining < {width}) return false;")
        if read_fn:
            w(f"    out = static_cast<{name}>({read_fn}(read_cursor));")
        else:
            w(f"    out = static_cast<{name}>(*read_cursor);")
        w(f"    read_cursor += {width};")
        w(f"    bytes_remaining -= {width};")
        w("    return true;")
        w("}")
        w("")

        # skip
        w(f"inline bool skip_{name}(const uint8_t*& read_cursor, std::size_t& bytes_remaining) {{")
        w(f"    if (bytes_remaining < {width}) return false;")
        w(f"    read_cursor += {width};")
        w(f"    bytes_remaining -= {width};")
        w("    return true;")
        w("}")
        w("")

        # max_decode_arena_bytes — enums need no arena
        w(f"inline constexpr std::size_t max_decode_arena_bytes_{name}([[maybe_unused]] std::size_t max_elements_per_list = 256) {{")
        w("    return 0;")
        w("}")
        w("")

        # max_encode_arena_bytes — enums need no arena
        w(f"inline constexpr std::size_t max_encode_arena_bytes_{name}([[maybe_unused]] std::size_t max_elements_per_list = 256) {{")
        w("    return 0;")
        w("}")

    # ------------------------------------------------------------------
    # Type mappings
    # ------------------------------------------------------------------

    def _cpp_int_type(self, name: str) -> str:
        mapping = {
            "i8":  "int8_t",
            "i16": "int16_t",
            "i32": "int32_t",
            "i64": "int64_t",
        }
        return mapping[name]

    def _cpp_primitive_type(self, name: str) -> str:
        mapping = {
            "i8":          "int8_t",
            "i16":         "int16_t",
            "i32":         "int32_t",
            "i64":         "int64_t",
            "bool":        "bool",
            "datetime_ns": "int64_t",
        }
        return mapping[name]

    def _cpp_type_owning(self, type_node) -> str:
        """Return the C++ type used in the owning (encode-side) struct."""
        if isinstance(type_node, PrimitiveType):
            return self._cpp_primitive_type(type_node.name)
        if isinstance(type_node, StringType):
            return "std::string_view"
        if isinstance(type_node, ArrayType):
            element_type = self._cpp_type_owning(type_node.element_type)
            return f"std::array<{element_type}, {type_node.length}>"
        if isinstance(type_node, ListType):
            element_type = self._cpp_type_owning(type_node.element_type)
            return f"ListView<{element_type}>"
        if isinstance(type_node, ReferenceType):
            return type_node.name
        raise RuntimeError(f"Unsupported type in owning struct: {type_node}")

    def _cpp_type_view(self, type_node, enum_names=None) -> str:
        """Return the C++ type used in the view (decode-side) struct.

        Enum types are fixed-size values with no separate View variant —
        they are used directly in both owning and view structs.
        """
        if isinstance(type_node, PrimitiveType):
            return self._cpp_primitive_type(type_node.name)
        if isinstance(type_node, StringType):
            return "std::string_view"
        if isinstance(type_node, ArrayType):
            element_type = self._cpp_type_view(type_node.element_type, enum_names)
            return f"std::array<{element_type}, {type_node.length}>"
        if isinstance(type_node, ListType):
            element_type = self._cpp_type_view(type_node.element_type, enum_names)
            return f"ListView<{element_type}>"
        if isinstance(type_node, ReferenceType):
            # Enums have no View variant — use the enum type name directly.
            if enum_names and type_node.name in enum_names:
                return type_node.name
            return f"{type_node.name}View"
        raise RuntimeError(f"Unsupported type in view struct: {type_node}")

    # ------------------------------------------------------------------
    # Message functions: declarations, size, encode, decode, skip
    # ------------------------------------------------------------------

    def _emit_message_functions(self, msg: MessageDecl, w, enum_names=None):
        name = msg.name

        w(f"[[nodiscard]] std::size_t encoded_size(const {name}& message);")
        w(f"[[nodiscard]] bool encode(const {name}& message,"  # pylint: disable=line-too-long
          f"    uint8_t* out_buffer, std::size_t out_size,"  # noqa
          f"    std::size_t& bytes_written, std::size_t& bytes_needed);")
        if self._is_fixed_size(msg, enum_names):
            w(f"inline void encode_fast(const {name}& message, uint8_t* out_buffer);")
        w(f"[[nodiscard]] bool decode_{name}({name}View& out, const uint8_t*& read_cursor, std::size_t& bytes_remaining, [[maybe_unused]] pubsub_itc_fw::BumpAllocator& decode_arena, [[maybe_unused]] std::size_t& arena_bytes_needed);")  # pylint: disable=line-too-long
        w(f"[[nodiscard]] bool skip_{name}(const uint8_t*& read_cursor, std::size_t& bytes_remaining);")
        w("")

        if self._is_fixed_size(msg, enum_names):
            self._emit_fixed_encoded_size(msg, w, enum_names)
            w("")
            self._emit_encode_fast_impl(msg, w, enum_names)
            w("")

        self._emit_encoded_size_impl(msg, w, enum_names)
        w("")
        self._emit_encode_impl(msg, w, enum_names)
        w("")
        self._emit_decode_view_impl(msg, w)
        w("")
        self._emit_skip_impl(msg, w)
        w("")
        self._emit_max_decode_arena_bytes(msg, w)
        w("")
        self._emit_max_encode_arena_bytes(msg, w)

    # ------------------------------------------------------------------
    # Fixed-size helpers
    # ------------------------------------------------------------------

    def _is_fixed_size(self, msg: MessageDecl, enum_names=None) -> bool:
        for field in msg.fields:
            if field.optional:
                return False
            if isinstance(field.type, PrimitiveType):
                continue
            if isinstance(field.type, ArrayType):
                if not isinstance(field.type.element_type, PrimitiveType):
                    return False
                continue
            if isinstance(field.type, ReferenceType):
                # Enum fields are fixed-size (encoded as their underlying integer type).
                if enum_names and field.type.name in enum_names:
                    continue
            return False
        return True

    def _emit_fixed_encoded_size(self, msg: MessageDecl, w, enum_names=None):
        w(f"inline constexpr std::size_t fixed_encoded_size(const {msg.name}&) {{")
        w("    std::size_t total_bytes = 0;")
        for field in msg.fields:
            self._emit_fixed_size_for_field(field, w, enum_names)
        w("    return total_bytes;")
        w("}")

    def _emit_fixed_size_for_field(self, field: Field, w, enum_names=None):
        type_node = field.type
        if isinstance(type_node, PrimitiveType):
            w(f"    total_bytes += sizeof({self._cpp_primitive_type(type_node.name)});")
        elif isinstance(type_node, ArrayType):
            element_cpp = self._cpp_primitive_type(type_node.element_type.name)
            w(f"    total_bytes += sizeof({element_cpp}) * {type_node.length};")
        elif isinstance(type_node, ReferenceType) and enum_names and type_node.name in enum_names:
            # Enum fields have a fixed wire size — delegate to the enum's encoded_size.
            w(f"    total_bytes += encoded_size({type_node.name}{{}});")
        else:
            raise RuntimeError(f"Non-fixed-size field in fixed size computation: {type_node}")

    def _emit_encode_fast_impl(self, msg: MessageDecl, w, enum_names=None):
        w(f"inline void encode_fast(const {msg.name}& message, uint8_t* out_buffer) {{")
        w("    uint8_t* write_cursor = out_buffer;")
        for field in msg.fields:
            self._emit_encode_fast_field(field, w, enum_names)
        w("}")

    def _emit_encode_fast_field(self, field: Field, w, enum_names=None):
        type_node = field.type
        name = field.name
        if isinstance(type_node, PrimitiveType):
            self._emit_encode_fast_primitive(type_node.name, f"message.{name}", w)
        elif isinstance(type_node, ArrayType):
            element_name = type_node.element_type.name
            if element_name == "i8":
                w(f"    std::memcpy(write_cursor, message.{name}.data(), {type_node.length});")
                w(f"    write_cursor += {type_node.length};")
            else:
                width = self._primitive_wire_size(element_name)
                w(f"    for (std::size_t i = 0; i < {type_node.length}; ++i) {{")
                self._emit_write_primitive(element_name, f"message.{name}[i]", "        ", w)
                w(f"        write_cursor += {width};")
                w("    }")
        elif isinstance(type_node, ReferenceType) and enum_names and type_node.name in enum_names:
            # Enum fields: encode via the enum's encode function, advancing write_cursor.
            w("    {")
            w("        std::size_t bw = 0, bn = 0;")
            w(f"        encode(message.{name}, write_cursor, encoded_size(message.{name}), bw, bn);")
            w("        write_cursor += bw;")
            w("    }")
        else:
            raise RuntimeError(f"Non-fixed-size field in encode_fast: {type_node}")

    def _emit_encode_fast_primitive(self, primitive_name: str, expr: str, w):
        width = self._primitive_wire_size(primitive_name)
        self._emit_write_primitive(primitive_name, expr, "    ", w)
        w(f"    write_cursor += {width};")

    # ------------------------------------------------------------------
    # encoded_size
    # ------------------------------------------------------------------

    def _emit_encoded_size_impl(self, msg: MessageDecl, w, enum_names=None):
        # For fixed-size messages the parameter is unused; delegate to fixed_encoded_size().
        if self._is_fixed_size(msg, enum_names):
            w(f"inline std::size_t encoded_size([[maybe_unused]] const {msg.name}& message) {{")
            w("    return fixed_encoded_size(message);")
            w("}")
            return
        w(f"inline std::size_t encoded_size(const {msg.name}& message) {{")
        w("    std::size_t total_bytes = 0;")
        for field in msg.fields:
            self._emit_size_for_field(field, w)
        w("    return total_bytes;")
        w("}")

    def _emit_size_for_field(self, field: Field, w):
        type_node = field.type
        name = field.name
        prefix = ""
        if field.optional:
            w("    total_bytes += 1;")
            prefix = f"if (message.has_{name}) "
        if isinstance(type_node, PrimitiveType):
            w(f"    {prefix}total_bytes += sizeof({self._cpp_primitive_type(type_node.name)});")
        elif isinstance(type_node, StringType):
            w(f"    {prefix}total_bytes += sizeof(std::uint32_t) + message.{name}.size();")
        elif isinstance(type_node, ArrayType):
            element_cpp = self._cpp_primitive_type(type_node.element_type.name)
            w(f"    {prefix}total_bytes += sizeof({element_cpp}) * {type_node.length};")
        elif isinstance(type_node, ListType):
            if prefix:
                w(f"    if (message.has_{name}) {{")
                self._emit_size_for_list(type_node, f"message.{name}", w, "        ")
                w("    }")
            else:
                self._emit_size_for_list(type_node, f"message.{name}", w, "    ")
        elif isinstance(type_node, ReferenceType):
            w(f"    {prefix}total_bytes += encoded_size(message.{name});")
        else:
            raise RuntimeError(f"Unknown field type in size: {type_node}")

    def _emit_size_for_list(self, list_type: ListType, expr: str, w, indent: str, loop_var: str = "i"):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner_indent = indent + "    "
        w(f"{indent}total_bytes += sizeof(std::uint32_t);")
        element_type = list_type.element_type
        if isinstance(element_type, PrimitiveType):
            element_cpp = self._cpp_primitive_type(element_type.name)
            w(f"{indent}total_bytes += sizeof({element_cpp}) * {expr}.size;")
        elif isinstance(element_type, StringType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}total_bytes += sizeof(std::uint32_t) + {expr}.data[{loop_var}].size();")
            w(f"{indent}}}")
        elif isinstance(element_type, ReferenceType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}total_bytes += encoded_size({expr}.data[{loop_var}]);")
            w(f"{indent}}}")
        elif isinstance(element_type, ListType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            self._emit_size_for_list(element_type, f"{expr}.data[{loop_var}]", w, inner_indent, next_var)
            w(f"{indent}}}")
        else:
            raise RuntimeError(f"Unsupported list element type in size: {element_type}")

    # ------------------------------------------------------------------
    # encode
    # ------------------------------------------------------------------

    def _emit_encode_impl(self, msg: MessageDecl, w, enum_names=None):
        name = msg.name
        w(f"inline bool encode(const {name}& message, uint8_t* out_buffer, std::size_t out_size, std::size_t& bytes_written, std::size_t& bytes_needed) {{")
        if self._is_fixed_size(msg, enum_names):
            w("    bytes_needed = fixed_encoded_size(message);")
            w("    if (out_size < bytes_needed) { bytes_written = 0; return false; }")
            w("    if (out_size == bytes_needed) {")
            w("        encode_fast(message, out_buffer);")
            w("        bytes_written = bytes_needed;")
            w("        return true;")
            w("    }")
        else:
            w("    bytes_needed = encoded_size(message);")
            w("    if (out_size < bytes_needed) { bytes_written = 0; return false; }")
        w("    uint8_t* write_cursor = out_buffer;")
        w("    std::size_t bytes_remaining = out_size;")
        for field in msg.fields:
            self._emit_encode_field(field, w)
        w("    bytes_written = static_cast<std::size_t>(write_cursor - out_buffer);")
        w("    return true;")
        w("}")

    def _emit_encode_field(self, field: Field, w):
        type_node = field.type
        name = field.name

        if field.optional:
            w("    if (bytes_remaining < 1) return false;")
            w(f"    *write_cursor = message.has_{name} ? 1 : 0;")
            w("    write_cursor += 1;")
            w("    bytes_remaining -= 1;")
            w(f"    if (!message.has_{name}) {{")
            w(f"        goto skip_field_{name};")
            w("    }")

        if isinstance(type_node, PrimitiveType):
            width = self._primitive_wire_size(type_node.name)
            w(f"    if (bytes_remaining < {width}) return false;")
            self._emit_write_primitive(type_node.name, f"message.{name}", "    ", w)
            w(f"    write_cursor += {width};")
            w(f"    bytes_remaining -= {width};")
        elif isinstance(type_node, StringType):
            w("    if (bytes_remaining < sizeof(std::uint32_t)) return false;")
            w(f"    std::uint32_t string_length_{name} = static_cast<std::uint32_t>(message.{name}.size());")
            w(f"    write_uint32_le(write_cursor, string_length_{name});")
            w("    write_cursor += sizeof(std::uint32_t);")
            w("    bytes_remaining -= sizeof(std::uint32_t);")
            w(f"    if (bytes_remaining < message.{name}.size()) return false;")
            w(f"    std::memcpy(write_cursor, message.{name}.data(), message.{name}.size());")
            w(f"    write_cursor += message.{name}.size();")
            w(f"    bytes_remaining -= message.{name}.size();")
        elif isinstance(type_node, ArrayType):
            self._emit_encode_array(type_node, name, w)
        elif isinstance(type_node, ListType):
            self._emit_encode_list(type_node, f"message.{name}", name, w, "    ")
        elif isinstance(type_node, ReferenceType):
            w("    {")
            w("        std::size_t element_bytes_written = 0;")
            w("        std::size_t element_bytes_needed = 0;")
            w(f"        if (!encode(message.{name}, write_cursor, bytes_remaining, element_bytes_written, element_bytes_needed)) return false;")
            w("        write_cursor += element_bytes_written;")
            w("        bytes_remaining -= element_bytes_written;")
            w("    }")
        else:
            raise RuntimeError(f"Unknown field type in encode: {type_node}")

        if field.optional:
            w(f"skip_field_{name}: ;")

    def _emit_encode_array(self, array_type: ArrayType, field_name: str, w):
        element_name = array_type.element_type.name
        length = array_type.length
        if element_name == "i8":
            w(f"    if (bytes_remaining < {length}) return false;")
            w(f"    std::memcpy(write_cursor, message.{field_name}.data(), {length});")
            w(f"    write_cursor += {length};")
            w(f"    bytes_remaining -= {length};")
        else:
            width = self._primitive_wire_size(element_name)
            w(f"    for (std::size_t i = 0; i < {length}; ++i) {{")
            w(f"        if (bytes_remaining < {width}) return false;")
            self._emit_write_primitive(element_name, f"message.{field_name}[i]", "        ", w)
            w(f"        write_cursor += {width};")
            w(f"        bytes_remaining -= {width};")
            w("    }")

    def _emit_encode_list(self, list_type: ListType, expr: str, suffix: str, w, indent: str, loop_var: str = "i"):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner_indent = indent + "    "
        w(f"{indent}if (bytes_remaining < sizeof(std::uint32_t)) return false;")
        w(f"{indent}write_uint32_le(write_cursor, static_cast<std::uint32_t>({expr}.size));")
        w(f"{indent}write_cursor += sizeof(std::uint32_t);")
        w(f"{indent}bytes_remaining -= sizeof(std::uint32_t);")
        element_type = list_type.element_type
        if isinstance(element_type, PrimitiveType):
            width = self._primitive_wire_size(element_type.name)
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}if (bytes_remaining < {width}) return false;")
            self._emit_write_primitive(element_type.name, f"{expr}.data[{loop_var}]", inner_indent, w)
            w(f"{inner_indent}write_cursor += {width};")
            w(f"{inner_indent}bytes_remaining -= {width};")
            w(f"{indent}}}")
        elif isinstance(element_type, StringType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}if (bytes_remaining < sizeof(std::uint32_t) + {expr}.data[{loop_var}].size()) return false;")
            w(f"{inner_indent}std::uint32_t string_length_{suffix}_{loop_var} = static_cast<std::uint32_t>({expr}.data[{loop_var}].size());")
            w(f"{inner_indent}write_uint32_le(write_cursor, string_length_{suffix}_{loop_var});")
            w(f"{inner_indent}write_cursor += sizeof(std::uint32_t);")
            w(f"{inner_indent}bytes_remaining -= sizeof(std::uint32_t);")
            w(f"{inner_indent}std::memcpy(write_cursor, {expr}.data[{loop_var}].data(), {expr}.data[{loop_var}].size());")
            w(f"{inner_indent}write_cursor += {expr}.data[{loop_var}].size();")
            w(f"{inner_indent}bytes_remaining -= {expr}.data[{loop_var}].size();")
            w(f"{indent}}}")
        elif isinstance(element_type, ReferenceType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}std::size_t element_bytes_written_{suffix} = 0;")
            w(f"{inner_indent}std::size_t element_bytes_needed_{suffix} = 0;")
            w(f"{inner_indent}if (!encode({expr}.data[{loop_var}], write_cursor, bytes_remaining, element_bytes_written_{suffix}, element_bytes_needed_{suffix})) return false;")  # pylint: disable=line-too-long
            w(f"{inner_indent}write_cursor += element_bytes_written_{suffix};")
            w(f"{inner_indent}bytes_remaining -= element_bytes_written_{suffix};")
            w(f"{indent}}}")
        elif isinstance(element_type, ListType):
            w(f"{indent}for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            self._emit_encode_list(element_type, f"{expr}.data[{loop_var}]", f"{suffix}_{loop_var}", w, inner_indent, next_var)
            w(f"{indent}}}")
        else:
            raise RuntimeError(f"Unsupported list element type in encode: {element_type}")

    # ------------------------------------------------------------------
    # decode
    # ------------------------------------------------------------------

    def _message_requires_arena(self, msg: MessageDecl) -> bool:
        """Return True if decoding this message requires any arena allocation.

        A message requires arena allocation if it has any list field whose
        element type is not a primitive — i.e. list<string>, list<Message>,
        list<list<T>>, or any nested message that itself requires arena allocation.
        """
        for field in msg.fields:
            if self._type_requires_arena(field.type):
                return True
        return False

    def _type_requires_arena(self, type_node) -> bool:
        """Return True if decoding this type requires any arena allocation."""
        if isinstance(type_node, ListType):
            element_type = type_node.element_type
            if isinstance(element_type, PrimitiveType):
                return False  # little-endian: zero-copy pointer into wire buffer
            return True  # string, message, or nested list all need arena
        if isinstance(type_node, ReferenceType):
            return True  # nested message may need arena (conservative)
        return False

    def _emit_decode_view_impl(self, msg: MessageDecl, w):
        name = msg.name
        requires_arena = self._message_requires_arena(msg)
        w(f"inline bool decode_{name}({name}View& out, const uint8_t*& read_cursor, std::size_t& bytes_remaining, [[maybe_unused]] pubsub_itc_fw::BumpAllocator& decode_arena, [[maybe_unused]] std::size_t& arena_bytes_needed) {{")  # pylint: disable=line-too-long
        if requires_arena:
            w("    bool arena_exhausted = false;")
        for field in msg.fields:
            self._emit_decode_field(field, w)
        if requires_arena:
            w("    return !arena_exhausted;")
        else:
            w("    return true;")
        w("}")

    def _emit_decode_field(self, field: Field, w):
        type_node = field.type
        fname = field.name

        if field.optional:
            w("    if (bytes_remaining < 1) return false;")
            w("    {")
            w("        std::uint8_t presence_flag = *read_cursor;")
            w("        read_cursor += 1;")
            w("        bytes_remaining -= 1;")
            w(f"        out.has_{fname} = (presence_flag != 0);")
            w(f"        if (!out.has_{fname}) goto skip_field_{fname};")
            w("    }")

        if isinstance(type_node, PrimitiveType):
            width = self._primitive_wire_size(type_node.name)
            cpp = self._cpp_primitive_type(type_node.name)
            w(f"    if (bytes_remaining < {width}) return false;")
            self._emit_read_primitive(type_node.name, cpp, f"out.{fname}", "    ", w)
            w(f"    read_cursor += {width};")
            w(f"    bytes_remaining -= {width};")
        elif isinstance(type_node, StringType):
            w("    if (bytes_remaining < sizeof(std::uint32_t)) return false;")
            w(f"    std::uint32_t len_{fname} = read_uint32_le(read_cursor);")
            w("    read_cursor += sizeof(std::uint32_t);")
            w("    bytes_remaining -= sizeof(std::uint32_t);")
            w(f"    if (bytes_remaining < static_cast<std::size_t>(len_{fname})) return false;")
            w(f"    out.{fname} = std::string_view(reinterpret_cast<const char*>(read_cursor), len_{fname});")
            w(f"    read_cursor += len_{fname};")
            w(f"    bytes_remaining -= static_cast<std::size_t>(len_{fname});")
        elif isinstance(type_node, ArrayType):
            self._emit_decode_array(type_node, fname, w)
        elif isinstance(type_node, ListType):
            self._emit_decode_list(type_node, f"out.{fname}", fname, w, "    ")
        elif isinstance(type_node, ReferenceType):
            w(f"    if (!decode_{type_node.name}(out.{fname}, read_cursor, bytes_remaining, decode_arena, arena_bytes_needed)) return false;")
        else:
            raise RuntimeError(f"Unknown field type in decode: {type_node}")

        if field.optional:
            w(f"skip_field_{fname}: ;")

    def _emit_decode_array(self, array_type: ArrayType, field_name: str, w):
        element_name = array_type.element_type.name
        element_cpp = self._cpp_primitive_type(element_name)
        length = array_type.length
        w(f"    for (std::size_t i = 0; i < {length}; ++i) {{")
        width = self._primitive_wire_size(element_name)
        w(f"        if (bytes_remaining < {width}) return false;")
        self._emit_read_primitive(element_name, element_cpp, f"out.{field_name}[i]", "        ", w)
        w(f"        read_cursor += {width};")
        w(f"        bytes_remaining -= {width};")
        w("    }")

    def _emit_decode_list(self, list_type: ListType, expr: str, suffix: str, w, indent: str, loop_var: str = "i"):  # pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-statements
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner_indent = indent + "    "
        w(f"{indent}if (bytes_remaining < sizeof(std::uint32_t)) return false;")
        w(f"{indent}{{")
        w(f"{inner_indent}std::uint32_t element_count_{suffix} = read_uint32_le(read_cursor);")
        w(f"{inner_indent}read_cursor += sizeof(std::uint32_t);")
        w(f"{inner_indent}bytes_remaining -= sizeof(std::uint32_t);")
        w(f"{inner_indent}{expr}.size = static_cast<std::size_t>(element_count_{suffix});")
        element_type = list_type.element_type
        if isinstance(element_type, PrimitiveType):
            element_cpp = self._cpp_primitive_type(element_type.name)
            width = self._primitive_wire_size(element_type.name)
            w(f"{inner_indent}{expr}.data = nullptr;")
            w(f"{inner_indent}if ({expr}.size > 0) {{")
            w(f"{inner_indent}#if HOST_IS_LITTLE_ENDIAN")
            w(f"{inner_indent}    std::size_t element_bytes_{suffix} = sizeof({element_cpp}) * {expr}.size;")
            w(f"{inner_indent}    if (bytes_remaining < element_bytes_{suffix}) return false;")
            w(f"{inner_indent}    {expr}.data = reinterpret_cast<{element_cpp}*>(const_cast<uint8_t*>(read_cursor));")
            w(f"{inner_indent}    read_cursor += element_bytes_{suffix};")
            w(f"{inner_indent}    bytes_remaining -= element_bytes_{suffix};")
            w(f"{inner_indent}#else")
            w(f"{inner_indent}    {{")
            w(f"{inner_indent}        std::size_t arena_aligned_offset = (arena_bytes_needed + alignof({element_cpp}) - 1) & ~(alignof({element_cpp}) - 1);")
            w(f"{inner_indent}        arena_bytes_needed = arena_aligned_offset + sizeof({element_cpp}) * {expr}.size;")
            w(f"{inner_indent}    }}")
            w(f"{inner_indent}    {expr}.data = decode_arena.allocate<{element_cpp}>({expr}.size);")
            w(f"{inner_indent}    if ({expr}.data == nullptr) arena_exhausted = true;")
            w(f"{inner_indent}    {element_cpp} dummy_primitive_{suffix}{{0}};")
            w(f"{inner_indent}    for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}        if (bytes_remaining < {width}) return false;")
            w(f"{inner_indent}        {element_cpp}& primitive_element_{suffix} = arena_exhausted ? dummy_primitive_{suffix} : {expr}.data[{loop_var}];")
            self._emit_read_primitive(element_type.name, element_cpp, f"primitive_element_{suffix}", inner_indent + "        ", w)
            w(f"{inner_indent}        read_cursor += {width};")
            w(f"{inner_indent}        bytes_remaining -= {width};")
            w(f"{inner_indent}    }}")
            w(f"{inner_indent}#endif")
            w(f"{inner_indent}}}")
        elif isinstance(element_type, StringType):
            w(f"{inner_indent}{{")
            w(f"{inner_indent}    std::size_t arena_aligned_offset = (arena_bytes_needed + alignof(std::string_view) - 1) & ~(alignof(std::string_view) - 1);")
            w(f"{inner_indent}    arena_bytes_needed = arena_aligned_offset + sizeof(std::string_view) * {expr}.size;")
            w(f"{inner_indent}}}")
            w(f"{inner_indent}{expr}.data = nullptr;")
            w(f"{inner_indent}if ({expr}.size > 0) {{")
            w(f"{inner_indent}    {expr}.data = decode_arena.allocate<std::string_view>({expr}.size);")
            w(f"{inner_indent}    if ({expr}.data == nullptr) arena_exhausted = true;")
            w(f"{inner_indent}    for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}        if (bytes_remaining < sizeof(std::uint32_t)) return false;")
            w(f"{inner_indent}        std::uint32_t str_len_{suffix}_{loop_var} = read_uint32_le(read_cursor);")
            w(f"{inner_indent}        read_cursor += sizeof(std::uint32_t);")
            w(f"{inner_indent}        bytes_remaining -= sizeof(std::uint32_t);")
            w(f"{inner_indent}        if (bytes_remaining < static_cast<std::size_t>(str_len_{suffix}_{loop_var})) return false;")
            w(f"{inner_indent}        if (!arena_exhausted) {{")
            w(f"{inner_indent}            {expr}.data[{loop_var}] = std::string_view(reinterpret_cast<const char*>(read_cursor), str_len_{suffix}_{loop_var});")
            w(f"{inner_indent}        }}")
            w(f"{inner_indent}        read_cursor += str_len_{suffix}_{loop_var};")
            w(f"{inner_indent}        bytes_remaining -= static_cast<std::size_t>(str_len_{suffix}_{loop_var});")
            w(f"{inner_indent}    }}")
            w(f"{inner_indent}}}")
        elif isinstance(element_type, ReferenceType):
            view_type = f"{element_type.name}View"
            w(f"{inner_indent}{{")
            w(f"{inner_indent}    std::size_t arena_aligned_offset = (arena_bytes_needed + alignof({element_type.name}View) - 1) & ~(alignof({element_type.name}View) - 1);")  # pylint: disable=line-too-long
            w(f"{inner_indent}    arena_bytes_needed = arena_aligned_offset + sizeof({element_type.name}View) * {expr}.size;")
            w(f"{inner_indent}}}")
            w(f"{inner_indent}{expr}.data = nullptr;")
            w(f"{inner_indent}if ({expr}.size > 0) {{")
            w(f"{inner_indent}    {expr}.data = decode_arena.allocate<{view_type}>({expr}.size);")
            w(f"{inner_indent}    if ({expr}.data == nullptr) arena_exhausted = true;")
            w(f"{inner_indent}    {view_type} dummy_{suffix}{{}};")
            w(f"{inner_indent}    for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}        {view_type}& element_{suffix} = arena_exhausted ? dummy_{suffix} : {expr}.data[{loop_var}];")
            w(f"{inner_indent}        element_{suffix} = {view_type}{{}};")
            w(f"{inner_indent}        if (!decode_{element_type.name}(element_{suffix}, read_cursor, bytes_remaining, decode_arena, arena_bytes_needed)) return false;")  # pylint: disable=line-too-long
            w(f"{inner_indent}    }}")
            w(f"{inner_indent}}}")
        elif isinstance(element_type, ListType):
            inner_element_cpp = self._cpp_type_view(element_type)
            w(f"{inner_indent}{{")
            w(f"{inner_indent}    std::size_t arena_aligned_offset = (arena_bytes_needed + alignof({inner_element_cpp}) - 1) & ~(alignof({inner_element_cpp}) - 1);")  # pylint: disable=line-too-long
            w(f"{inner_indent}    arena_bytes_needed = arena_aligned_offset + sizeof({inner_element_cpp}) * {expr}.size;")
            w(f"{inner_indent}}}")
            w(f"{inner_indent}{expr}.data = nullptr;")
            w(f"{inner_indent}if ({expr}.size > 0) {{")
            w(f"{inner_indent}    {expr}.data = decode_arena.allocate<{inner_element_cpp}>({expr}.size);")
            w(f"{inner_indent}    if ({expr}.data == nullptr) arena_exhausted = true;")
            w(f"{inner_indent}    {inner_element_cpp} dummy_{suffix}{{}};")
            w(f"{inner_indent}    for (std::size_t {loop_var} = 0; {loop_var} < {expr}.size; ++{loop_var}) {{")
            w(f"{inner_indent}        {inner_element_cpp}& element_{suffix} = arena_exhausted ? dummy_{suffix} : {expr}.data[{loop_var}];")
            w(f"{inner_indent}        element_{suffix} = {inner_element_cpp}{{}};")
            self._emit_decode_list(element_type, f"element_{suffix}", f"{suffix}_{loop_var}", w, inner_indent + "        ", next_var)
            w(f"{inner_indent}    }}")
            w(f"{inner_indent}}}")
        else:
            raise RuntimeError(f"Unsupported list element type in decode: {element_type}")
        w(f"{indent}}}")

    # ------------------------------------------------------------------
    # skip
    # ------------------------------------------------------------------

    def _emit_skip_impl(self, msg: MessageDecl, w):
        w(f"inline bool skip_{msg.name}(const uint8_t*& read_cursor, std::size_t& bytes_remaining) {{")
        for field in msg.fields:
            self._emit_skip_field(field, w)
        w("    return true;")
        w("}")

    def _emit_skip_field(self, field: Field, w):
        type_node = field.type
        name = field.name

        if field.optional:
            w("    if (bytes_remaining < 1) return false;")
            w("    {")
            w("        std::uint8_t presence_flag = *read_cursor;")
            w("        read_cursor += 1;")
            w("        bytes_remaining -= 1;")
            w(f"        if (!presence_flag) goto skip_field_{name};")
            w("    }")

        if isinstance(type_node, PrimitiveType):
            width = self._primitive_wire_size(type_node.name)
            w(f"    if (bytes_remaining < {width}) return false;")
            w(f"    read_cursor += {width};")
            w(f"    bytes_remaining -= {width};")
        elif isinstance(type_node, StringType):
            w("    if (bytes_remaining < sizeof(std::uint32_t)) return false;")
            w("    {")
            w("        std::uint32_t str_len = read_uint32_le(read_cursor);")
            w("        read_cursor += sizeof(std::uint32_t);")
            w("        bytes_remaining -= sizeof(std::uint32_t);")
            w("        if (bytes_remaining < static_cast<std::size_t>(str_len)) return false;")
            w("        read_cursor += str_len;")
            w("        bytes_remaining -= static_cast<std::size_t>(str_len);")
            w("    }")
        elif isinstance(type_node, ArrayType):
            total = f"{type_node.length} * {self._primitive_wire_size(type_node.element_type.name)}"
            w(f"    if (bytes_remaining < {total}) return false;")
            w(f"    read_cursor += {total};")
            w(f"    bytes_remaining -= {total};")
        elif isinstance(type_node, ListType):
            self._emit_skip_list(type_node, w, "    ", "i")
        elif isinstance(type_node, ReferenceType):
            w(f"    if (!skip_{type_node.name}(read_cursor, bytes_remaining)) return false;")
        else:
            raise RuntimeError(f"Unknown field type in skip: {type_node}")

        if field.optional:
            w(f"skip_field_{name}: ;")

    def _emit_skip_list(self, list_type: ListType, w, indent: str, loop_var: str):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner_indent = indent + "    "
        w(f"{indent}if (bytes_remaining < sizeof(std::uint32_t)) return false;")
        w(f"{indent}{{")
        w(f"{inner_indent}std::uint32_t skip_count = read_uint32_le(read_cursor);")
        w(f"{inner_indent}read_cursor += sizeof(std::uint32_t);")
        w(f"{inner_indent}bytes_remaining -= sizeof(std::uint32_t);")
        element_type = list_type.element_type
        if isinstance(element_type, PrimitiveType):
            element_cpp = self._cpp_primitive_type(element_type.name)
            w(f"{inner_indent}std::size_t skip_bytes = sizeof({element_cpp}) * static_cast<std::size_t>(skip_count);")
            w(f"{inner_indent}if (bytes_remaining < skip_bytes) return false;")
            w(f"{inner_indent}read_cursor += skip_bytes;")
            w(f"{inner_indent}bytes_remaining -= skip_bytes;")
        elif isinstance(element_type, StringType):
            w(f"{inner_indent}for (std::size_t {loop_var} = 0; {loop_var} < skip_count; ++{loop_var}) {{")
            w(f"{inner_indent}    if (bytes_remaining < sizeof(std::uint32_t)) return false;")
            w(f"{inner_indent}    std::uint32_t str_len = read_uint32_le(read_cursor);")
            w(f"{inner_indent}    read_cursor += sizeof(std::uint32_t);")
            w(f"{inner_indent}    bytes_remaining -= sizeof(std::uint32_t);")
            w(f"{inner_indent}    if (bytes_remaining < static_cast<std::size_t>(str_len)) return false;")
            w(f"{inner_indent}    read_cursor += str_len;")
            w(f"{inner_indent}    bytes_remaining -= static_cast<std::size_t>(str_len);")
            w(f"{inner_indent}}}")
        elif isinstance(element_type, ReferenceType):
            w(f"{inner_indent}for (std::size_t {loop_var} = 0; {loop_var} < skip_count; ++{loop_var}) {{")
            w(f"{inner_indent}    if (!skip_{element_type.name}(read_cursor, bytes_remaining)) return false;")
            w(f"{inner_indent}}}")
        elif isinstance(element_type, ListType):
            w(f"{inner_indent}for (std::size_t {loop_var} = 0; {loop_var} < skip_count; ++{loop_var}) {{")
            self._emit_skip_list(element_type, w, inner_indent + "    ", next_var)
            w(f"{inner_indent}}}")
        else:
            raise RuntimeError(f"Unsupported list element type in skip: {element_type}")
        w(f"{indent}}}")

    # ------------------------------------------------------------------
    # decode wrapper (public API)
    # ------------------------------------------------------------------

    def _emit_decode_wrapper(self, msg: MessageDecl, w):
        name = msg.name
        view = f"{name}View"
        w(f"[[nodiscard]] inline bool decode({view}& out,")
        w("                                 const uint8_t* buffer,")
        w("                                 std::size_t bytes_available,")
        w("                                 std::size_t& bytes_consumed,")
        w("                                 [[maybe_unused]] pubsub_itc_fw::BumpAllocator& decode_arena,")
        w("                                 std::size_t& arena_bytes_needed)")
        w("{")
        w("    const uint8_t* cursor = buffer;")
        w("    std::size_t remaining = bytes_available;")
        w("    arena_bytes_needed = 0;")
        w(f"    if (!decode_{name}(out, cursor, remaining, decode_arena, arena_bytes_needed)) {{")
        w("        return false;")
        w("    }")
        w("    bytes_consumed = bytes_available - remaining;")
        w("    return true;")
        w("}")

    # ------------------------------------------------------------------
    # Arena sizing helpers
    # ------------------------------------------------------------------

    def _emit_max_decode_arena_bytes(self, msg: MessageDecl, w):
        w(f"inline constexpr std::size_t max_decode_arena_bytes_{msg.name}([[maybe_unused]] std::size_t max_elements_per_list = 256) {{")
        w("    std::size_t total = 0;")
        for field in msg.fields:
            self._emit_decode_arena_size_for_field(field.type, "total", w, "    ", max_depth=8)
        w("    return total;")
        w("}")

    def _emit_decode_arena_size_for_field(self, type_node, total_var: str, w, indent: str, max_depth: int):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        if max_depth == 0:
            return
        if isinstance(type_node, ListType):
            element_type = type_node.element_type
            if isinstance(element_type, PrimitiveType):
                element_cpp = self._cpp_primitive_type(element_type.name)
                w(f"{indent}{total_var} += sizeof({element_cpp}) * max_elements_per_list;")
            elif isinstance(element_type, StringType):
                w(f"{indent}{total_var} += sizeof(std::string_view) * max_elements_per_list;")
            elif isinstance(element_type, ReferenceType):
                w(f"{indent}{total_var} += sizeof({element_type.name}View) * max_elements_per_list;")
                w(f"{indent}{total_var} += max_elements_per_list * max_decode_arena_bytes_{element_type.name}(max_elements_per_list);")
            elif isinstance(element_type, ListType):
                inner_cpp = self._cpp_type_view(element_type)
                w(f"{indent}{total_var} += sizeof(ListView<{inner_cpp}>) * max_elements_per_list;")
                self._emit_decode_arena_size_for_field(element_type, total_var, w, indent, max_depth - 1)
        elif isinstance(type_node, ReferenceType):
            w(f"{indent}{total_var} += max_decode_arena_bytes_{type_node.name}(max_elements_per_list);")

    def _emit_max_encode_arena_bytes(self, msg: MessageDecl, w):
        w(f"inline constexpr std::size_t max_encode_arena_bytes_{msg.name}([[maybe_unused]] std::size_t max_elements_per_list = 256) {{")
        w("    std::size_t total = 0;")
        for field in msg.fields:
            self._emit_encode_arena_size_for_field(field.type, "total", w, "    ", max_depth=8)
        w("    return total;")
        w("}")

    def _emit_encode_arena_size_for_field(self, type_node, total_var: str, w, indent: str, max_depth: int):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        if max_depth == 0:
            return
        if isinstance(type_node, ListType):
            element_type = type_node.element_type
            if isinstance(element_type, PrimitiveType):
                element_cpp = self._cpp_primitive_type(element_type.name)
                w(f"{indent}{total_var} += sizeof({element_cpp}) * max_elements_per_list;")
            elif isinstance(element_type, StringType):
                w(f"{indent}{total_var} += sizeof(std::string_view) * max_elements_per_list;")
            elif isinstance(element_type, ReferenceType):
                w(f"{indent}{total_var} += sizeof({element_type.name}) * max_elements_per_list;")
                w(f"{indent}{total_var} += max_elements_per_list * max_encode_arena_bytes_{element_type.name}(max_elements_per_list);")
            elif isinstance(element_type, ListType):
                inner_cpp = self._cpp_type_owning(element_type)
                w(f"{indent}{total_var} += sizeof(ListView<{inner_cpp}>) * max_elements_per_list;")
                self._emit_encode_arena_size_for_field(element_type, total_var, w, indent, max_depth - 1)
        elif isinstance(type_node, ReferenceType):
            w(f"{indent}{total_var} += max_encode_arena_bytes_{type_node.name}(max_elements_per_list);")

    # ------------------------------------------------------------------
    # Primitive wire-format helpers
    # ------------------------------------------------------------------

    def _primitive_wire_size(self, primitive_name: str) -> int:
        sizes = {
            "i8":          1,
            "bool":        1,
            "i16":         2,
            "i32":         4,
            "i64":         8,
            "datetime_ns": 8,
        }
        return sizes[primitive_name]

    def _emit_write_primitive(self, primitive_name: str, expr: str, indent: str, w):
        if primitive_name == "i8":
            w(f"{indent}*write_cursor = static_cast<std::uint8_t>({expr});")
        elif primitive_name == "bool":
            w(f"{indent}*write_cursor = {expr} ? 1 : 0;")
        elif primitive_name == "i16":
            w(f"{indent}write_uint16_le(write_cursor, static_cast<std::uint16_t>({expr}));")
        elif primitive_name == "i32":
            w(f"{indent}write_uint32_le(write_cursor, static_cast<std::uint32_t>({expr}));")
        elif primitive_name in ("i64", "datetime_ns"):
            w(f"{indent}write_uint64_le(write_cursor, static_cast<std::uint64_t>({expr}));")
        else:
            raise RuntimeError(f"Unsupported primitive type in write: {primitive_name}")

    def _emit_read_primitive(self, primitive_name: str, cpp_type: str, target: str, indent: str, w):  # pylint: disable=too-many-arguments,too-many-positional-arguments
        if primitive_name == "i8":
            w(f"{indent}{target} = static_cast<{cpp_type}>(*read_cursor);")
        elif primitive_name == "bool":
            w(f"{indent}{target} = (*read_cursor != 0);")
        elif primitive_name == "i16":
            w(f"{indent}{target} = static_cast<{cpp_type}>(read_uint16_le(read_cursor));")
        elif primitive_name == "i32":
            w(f"{indent}{target} = static_cast<{cpp_type}>(read_uint32_le(read_cursor));")
        elif primitive_name in ("i64", "datetime_ns"):
            w(f"{indent}{target} = static_cast<{cpp_type}>(read_uint64_le(read_cursor));")
        else:
            raise RuntimeError(f"Unsupported primitive type in read: {primitive_name}")
