"""Java code generator for the pubsub_itc_fw DSL."""
# pylint: disable=too-many-lines

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Set

from .ast import (
    ArrayType,
    BytesType,
    DslFile,
    EnumDecl,
    Field,
    ListType,
    MessageDecl,
    PrimitiveType,
    ReferenceType,
    StringType,
)


@dataclass
class JavaGenerator:
    """Generates a Java source file from a validated DSL AST.

    The generated file contains a single public final outer class acting as a
    namespace container for:
      - One public enum per DSL enum declaration
      - One public static final inner class per DSL message, with:
          - Public fields with zero/empty defaults
          - static encodedSize(MsgType) -> int
          - static encode(MsgType, ByteBuffer) -> int  (bytes written, or -1)
          - static decode(ByteBuffer) -> MsgType | null
          - package-private static _decodeFields(ByteBuffer) for nested calls

    Wire format is little-endian throughout, matching the C++ generator.
    ByteBuffer.order(ByteOrder.LITTLE_ENDIAN) is applied at the start of every
    encode and decode call.
    """

    class_name: str
    package_name: str = ""

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def emit(self, ast: DslFile) -> str:
        """Generate and return the complete Java source file as a string."""
        lines: List[str] = []
        w = lines.append

        self._emit_preamble(w)
        if self.package_name:
            w(f"package {self.package_name};")
            w("")
        w("import java.nio.ByteBuffer;")
        w("import java.nio.ByteOrder;")
        w("import java.nio.charset.StandardCharsets;")
        w("")
        w(f"public final class {self.class_name} {{")
        w("")

        enum_names: Set[str] = {d.name for d in ast.declarations if isinstance(d, EnumDecl)}
        enum_decls: Dict[str, EnumDecl] = {
            d.name: d for d in ast.declarations if isinstance(d, EnumDecl)
        }

        for decl in ast.declarations:
            if isinstance(decl, EnumDecl):
                self._emit_enum(decl, w)
                w("")

        for decl in ast.declarations:
            if isinstance(decl, MessageDecl):
                self._emit_message(decl, w, enum_names, enum_decls)
                w("")

        w(f"}} // class {self.class_name}")
        w("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Preamble
    # ------------------------------------------------------------------

    def _emit_preamble(self, w) -> None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        w("// -----------------------------------------------------------------------------")
        w("//  This file was automatically generated by the DSL code generator.")
        w("//  Do NOT edit this file manually.")
        w("//")
        w(f"//  Generated on: {timestamp}")
        w("// -----------------------------------------------------------------------------")
        w("")

    # ------------------------------------------------------------------
    # Enum
    # ------------------------------------------------------------------

    def _emit_enum(self, enum: EnumDecl, w) -> None:
        value_type = "long" if enum.underlying_type == "i64" else "int"
        w(f"    public enum {enum.name} {{")
        for index, entry in enumerate(enum.entries):
            sep = "," if index + 1 < len(enum.entries) else ";"
            w(f"        {entry.name}({entry.value}){sep}")
        w(f"        public final {value_type} value;")
        w(f"        {enum.name}({value_type} v) {{ this.value = v; }}")
        w(f"        public static {enum.name} fromValue({value_type} v) {{")
        w(f"            for ({enum.name} e : values()) {{ if (e.value == v) return e; }}")
        w("            return null;")
        w("        }")
        w("        public static int wireSize() {")
        w(f"            return {self._primitive_wire_size(enum.underlying_type)};")
        w("        }")
        w("    }")

    # ------------------------------------------------------------------
    # Message class
    # ------------------------------------------------------------------

    def _emit_message(self, msg: MessageDecl, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl]) -> None:
        w(f"    public static final class {msg.name} {{")
        for field in msg.fields:
            if field.optional:
                w(f"        public boolean has_{field.name} = false;")
            java_type = self._java_type(field.type, enum_names)
            default = self._java_default(field.type, enum_names)
            w(f"        public {java_type} {field.name} = {default};")
        w("")
        self._emit_encoded_size(msg, w, enum_names, enum_decls)
        w("")
        self._emit_encode(msg, w, enum_names, enum_decls)
        w("")
        self._emit_decode_public(msg, w)
        w("")
        self._emit_decode_fields(msg, w, enum_names, enum_decls)
        w("    }")

    # ------------------------------------------------------------------
    # encodedSize
    # ------------------------------------------------------------------

    def _emit_encoded_size(self, msg: MessageDecl, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl]) -> None:
        w(f"        public static int encodedSize({msg.name} msg) {{")
        w("            int total = 0;")
        for field in msg.fields:
            self._emit_size_for_field(field, w, enum_names, enum_decls, "            ")
        w("            return total;")
        w("        }")

    def _emit_size_for_field(self, field: Field, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str) -> None:  # pylint: disable=too-many-arguments
        name = field.name
        if field.optional:
            w(f"{indent}total += 1;")
            w(f"{indent}if (msg.has_{name}) {{")
            self._emit_size_for_type(field.type, f"msg.{name}", w, enum_names, enum_decls, indent + "    ")
            w(f"{indent}}}")
        else:
            self._emit_size_for_type(field.type, f"msg.{name}", w, enum_names, enum_decls, indent)

    def _emit_size_for_type(self, type_node, expr: str, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str) -> None:  # pylint: disable=too-many-arguments
        if isinstance(type_node, PrimitiveType):
            w(f"{indent}total += {self._primitive_wire_size(type_node.name)};")
        elif isinstance(type_node, StringType):
            w(f"{indent}total += 4 + {expr}.getBytes(StandardCharsets.UTF_8).length;")
        elif isinstance(type_node, BytesType):
            w(f"{indent}total += 4 + {expr}.length;")
        elif isinstance(type_node, ArrayType):
            elem_size = self._primitive_wire_size(type_node.element_type.name)
            w(f"{indent}total += {elem_size} * {type_node.length};")
        elif isinstance(type_node, ListType):
            self._emit_size_for_list(type_node, expr, w, enum_names, enum_decls, indent)
        elif isinstance(type_node, ReferenceType):
            if type_node.name in enum_names:
                wire_size = self._primitive_wire_size(enum_decls[type_node.name].underlying_type)
                w(f"{indent}total += {wire_size};")
            else:
                w(f"{indent}total += {type_node.name}.encodedSize({expr});")
        else:
            raise RuntimeError(f"Unknown type in Java encodedSize: {type_node}")

    def _emit_size_for_list(  # pylint: disable=too-many-arguments
            self, list_type: ListType, expr: str, w,
            enum_names: Set[str], enum_decls: Dict[str, EnumDecl],
            indent: str, loop_var: str = "i") -> None:
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner = indent + "    "
        w(f"{indent}total += 4;")
        elem_type = list_type.element_type
        if isinstance(elem_type, PrimitiveType):
            w(f"{indent}total += {self._primitive_wire_size(elem_type.name)} * {expr}.length;")
        elif isinstance(elem_type, StringType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            w(f"{inner}total += 4 + {expr}[{loop_var}].getBytes(StandardCharsets.UTF_8).length;")
            w(f"{indent}}}")
        elif isinstance(elem_type, BytesType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            w(f"{inner}total += 4 + {expr}[{loop_var}].length;")
            w(f"{indent}}}")
        elif isinstance(elem_type, ReferenceType):
            if elem_type.name in enum_names:
                wire_size = self._primitive_wire_size(enum_decls[elem_type.name].underlying_type)
                w(f"{indent}total += {wire_size} * {expr}.length;")
            else:
                w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
                w(f"{inner}total += {elem_type.name}.encodedSize({expr}[{loop_var}]);")
                w(f"{indent}}}")
        elif isinstance(elem_type, ListType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            self._emit_size_for_list(elem_type, f"{expr}[{loop_var}]", w, enum_names, enum_decls, inner, next_var)
            w(f"{indent}}}")
        else:
            raise RuntimeError(f"Unknown list element type in Java size: {elem_type}")

    # ------------------------------------------------------------------
    # encode
    # ------------------------------------------------------------------

    def _emit_encode(self, msg: MessageDecl, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl]) -> None:
        w(f"        public static int encode({msg.name} msg, ByteBuffer buf) {{")
        w("            buf.order(ByteOrder.LITTLE_ENDIAN);")
        w("            int needed = encodedSize(msg);")
        w("            if (buf.remaining() < needed) return -1;")
        w("            int startPos = buf.position();")
        for field in msg.fields:
            self._emit_encode_field(field, w, enum_names, enum_decls, "            ")
        w("            return buf.position() - startPos;")
        w("        }")

    def _emit_encode_field(self, field: Field, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str) -> None:  # pylint: disable=too-many-arguments
        name = field.name
        if field.optional:
            w(f"{indent}buf.put(msg.has_{name} ? (byte) 1 : (byte) 0);")
            w(f"{indent}if (msg.has_{name}) {{")
            self._emit_encode_type(field.type, f"msg.{name}", w, enum_names, enum_decls, indent + "    ")
            w(f"{indent}}}")
        else:
            self._emit_encode_type(field.type, f"msg.{name}", w, enum_names, enum_decls, indent)

    def _emit_encode_type(self, type_node, expr: str, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str) -> None:  # pylint: disable=too-many-arguments
        if isinstance(type_node, PrimitiveType):
            w(f"{indent}{self._emit_buf_put(type_node.name, expr)};")
        elif isinstance(type_node, StringType):
            w(f"{indent}{{")
            inner = indent + "    "
            w(f"{inner}byte[] _strBytes = {expr}.getBytes(StandardCharsets.UTF_8);")
            w(f"{inner}buf.putInt(_strBytes.length);")
            w(f"{inner}buf.put(_strBytes);")
            w(f"{indent}}}")
        elif isinstance(type_node, BytesType):
            w(f"{indent}buf.putInt({expr}.length);")
            w(f"{indent}buf.put({expr});")
        elif isinstance(type_node, ArrayType):
            elem_name = type_node.element_type.name
            w(f"{indent}for (int _i = 0; _i < {type_node.length}; _i++) {{")
            w(f"{indent}    {self._emit_buf_put(elem_name, expr + '[_i]')};")
            w(f"{indent}}}")
        elif isinstance(type_node, ListType):
            self._emit_encode_list(type_node, expr, w, enum_names, enum_decls, indent)
        elif isinstance(type_node, ReferenceType):
            if type_node.name in enum_names:
                underlying = enum_decls[type_node.name].underlying_type
                w(f"{indent}{self._emit_buf_put_enum(underlying, expr)};")
            else:
                w(f"{indent}{type_node.name}.encode({expr}, buf);")
        else:
            raise RuntimeError(f"Unknown type in Java encode: {type_node}")

    def _emit_encode_list(  # pylint: disable=too-many-arguments
            self, list_type: ListType, expr: str, w,
            enum_names: Set[str], enum_decls: Dict[str, EnumDecl],
            indent: str, loop_var: str = "i") -> None:
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner = indent + "    "
        w(f"{indent}buf.putInt({expr}.length);")
        elem_type = list_type.element_type
        if isinstance(elem_type, PrimitiveType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            w(f"{inner}{self._emit_buf_put(elem_type.name, f'{expr}[{loop_var}]')};")
            w(f"{indent}}}")
        elif isinstance(elem_type, StringType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            lv = loop_var.upper()
            w(f"{inner}byte[] _elemBytes{lv} = {expr}[{loop_var}].getBytes(StandardCharsets.UTF_8);")
            w(f"{inner}buf.putInt(_elemBytes{lv}.length);")
            w(f"{inner}buf.put(_elemBytes{lv});")
            w(f"{indent}}}")
        elif isinstance(elem_type, BytesType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            w(f"{inner}buf.putInt({expr}[{loop_var}].length);")
            w(f"{inner}buf.put({expr}[{loop_var}]);")
            w(f"{indent}}}")
        elif isinstance(elem_type, ReferenceType):
            if elem_type.name in enum_names:
                underlying = enum_decls[elem_type.name].underlying_type
                w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
                w(f"{inner}{self._emit_buf_put_enum(underlying, f'{expr}[{loop_var}]')};")
                w(f"{indent}}}")
            else:
                w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
                w(f"{inner}{elem_type.name}.encode({expr}[{loop_var}], buf);")
                w(f"{indent}}}")
        elif isinstance(elem_type, ListType):
            w(f"{indent}for (int {loop_var} = 0; {loop_var} < {expr}.length; {loop_var}++) {{")
            self._emit_encode_list(elem_type, f"{expr}[{loop_var}]", w, enum_names, enum_decls, inner, next_var)
            w(f"{indent}}}")
        else:
            raise RuntimeError(f"Unknown list element type in Java encode: {elem_type}")

    # ------------------------------------------------------------------
    # decode (public wrapper + _decodeFields)
    # ------------------------------------------------------------------

    def _emit_decode_public(self, msg: MessageDecl, w) -> None:
        name = msg.name
        w(f"        public static {name} decode(ByteBuffer buf) {{")
        w("            buf.order(ByteOrder.LITTLE_ENDIAN);")
        w("            int startPos = buf.position();")
        w("            try {")
        w("                return _decodeFields(buf);")
        w("            } catch (java.nio.BufferUnderflowException e) {")
        w("                buf.position(startPos);")
        w("                return null;")
        w("            }")
        w("        }")

    def _emit_decode_fields(self, msg: MessageDecl, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl]) -> None:
        name = msg.name
        w(f"        static {name} _decodeFields(ByteBuffer buf) {{")
        w(f"            {name} out = new {name}();")
        for field in msg.fields:
            self._emit_decode_field(field, w, enum_names, enum_decls, "            ")
        w("            return out;")
        w("        }")

    def _emit_decode_field(self, field: Field, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str) -> None:  # pylint: disable=too-many-arguments
        name = field.name
        if field.optional:
            w(f"{indent}out.has_{name} = (buf.get() != 0);")
            w(f"{indent}if (out.has_{name}) {{")
            self._emit_decode_type(field.type, f"out.{name}", w, enum_names, enum_decls, indent + "    ")
            w(f"{indent}}}")
        else:
            self._emit_decode_type(field.type, f"out.{name}", w, enum_names, enum_decls, indent)

    def _emit_decode_type(self, type_node, target: str, w, enum_names: Set[str], enum_decls: Dict[str, EnumDecl], indent: str, loop_var: str = "i") -> None:  # pylint: disable=too-many-arguments
        if isinstance(type_node, PrimitiveType):
            w(f"{indent}{target} = {self._emit_buf_get(type_node.name)};")
        elif isinstance(type_node, StringType):
            w(f"{indent}{{")
            inner = indent + "    "
            w(f"{inner}int _strLen = buf.getInt();")
            w(f"{inner}byte[] _strBytes = new byte[_strLen];")
            w(f"{inner}buf.get(_strBytes);")
            w(f"{inner}{target} = new String(_strBytes, StandardCharsets.UTF_8);")
            w(f"{indent}}}")
        elif isinstance(type_node, BytesType):
            w(f"{indent}{{")
            inner = indent + "    "
            w(f"{inner}int _bytesLen = buf.getInt();")
            w(f"{inner}{target} = new byte[_bytesLen];")
            w(f"{inner}buf.get({target});")
            w(f"{indent}}}")
        elif isinstance(type_node, ArrayType):
            elem_name = type_node.element_type.name
            java_elem = self._java_primitive(elem_name)
            w(f"{indent}{target} = new {java_elem}[{type_node.length}];")
            w(f"{indent}for (int _i = 0; _i < {type_node.length}; _i++) {{")
            w(f"{indent}    {target}[_i] = {self._emit_buf_get(elem_name)};")
            w(f"{indent}}}")
        elif isinstance(type_node, ListType):
            self._emit_decode_list(type_node, target, w, enum_names, enum_decls, indent, loop_var)
        elif isinstance(type_node, ReferenceType):
            if type_node.name in enum_names:
                underlying = enum_decls[type_node.name].underlying_type
                w(f"{indent}{target} = {type_node.name}.fromValue({self._emit_buf_get_enum(underlying)});")
            else:
                w(f"{indent}{target} = {type_node.name}._decodeFields(buf);")
        else:
            raise RuntimeError(f"Unknown type in Java decode: {type_node}")

    def _emit_decode_list(  # pylint: disable=too-many-arguments
            self, list_type: ListType, target: str, w,
            enum_names: Set[str], enum_decls: Dict[str, EnumDecl],
            indent: str, loop_var: str = "i") -> None:
        next_var = chr(ord(loop_var) + 1) if loop_var < "z" else loop_var + "_"
        inner = indent + "    "
        count_var = f"count_{loop_var}"
        elem_type = list_type.element_type
        elem_java_type = self._java_type(elem_type, enum_names)
        w(f"{indent}{{")
        w(f"{inner}int {count_var} = buf.getInt();")
        w(f"{inner}{target} = {self._java_new_array(elem_java_type, count_var)};")
        if isinstance(elem_type, PrimitiveType):
            w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
            w(f"{inner}    {target}[{loop_var}] = {self._emit_buf_get(elem_type.name)};")
            w(f"{inner}}}")
        elif isinstance(elem_type, StringType):
            lv = loop_var.upper()
            w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
            w(f"{inner}    int _strLen{lv} = buf.getInt();")
            w(f"{inner}    byte[] _strBytes{lv} = new byte[_strLen{lv}];")
            w(f"{inner}    buf.get(_strBytes{lv});")
            w(f"{inner}    {target}[{loop_var}] = new String(_strBytes{lv}, StandardCharsets.UTF_8);")
            w(f"{inner}}}")
        elif isinstance(elem_type, BytesType):
            lv = loop_var.upper()
            w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
            w(f"{inner}    int _bytesLen{lv} = buf.getInt();")
            w(f"{inner}    {target}[{loop_var}] = new byte[_bytesLen{lv}];")
            w(f"{inner}    buf.get({target}[{loop_var}]);")
            w(f"{inner}}}")
        elif isinstance(elem_type, ReferenceType):
            if elem_type.name in enum_names:
                underlying = enum_decls[elem_type.name].underlying_type
                w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
                w(f"{inner}    {target}[{loop_var}] = {elem_type.name}.fromValue({self._emit_buf_get_enum(underlying)});")
                w(f"{inner}}}")
            else:
                w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
                w(f"{inner}    {target}[{loop_var}] = {elem_type.name}._decodeFields(buf);")
                w(f"{inner}}}")
        elif isinstance(elem_type, ListType):
            w(f"{inner}for (int {loop_var} = 0; {loop_var} < {count_var}; {loop_var}++) {{")
            self._emit_decode_list(elem_type, f"{target}[{loop_var}]", w, enum_names, enum_decls, inner + "    ", next_var)
            w(f"{inner}}}")
        else:
            raise RuntimeError(f"Unknown list element type in Java decode: {elem_type}")
        w(f"{indent}}}")

    # ------------------------------------------------------------------
    # Type system helpers
    # ------------------------------------------------------------------

    def _java_primitive(self, name: str) -> str:
        return {
            "i8":          "byte",
            "char":        "byte",   # Java char is 2-byte UTF-16; DSL char is a 1-byte value
            "i16":         "short",
            "i32":         "int",
            "i64":         "long",
            "bool":        "boolean",
            "datetime_ns": "long",
        }[name]

    def _java_type(self, type_node, enum_names: Set[str]) -> str:
        if isinstance(type_node, PrimitiveType):
            return self._java_primitive(type_node.name)
        if isinstance(type_node, StringType):
            return "String"
        if isinstance(type_node, BytesType):
            return "byte[]"
        if isinstance(type_node, ListType):
            return self._java_type(type_node.element_type, enum_names) + "[]"
        if isinstance(type_node, ArrayType):
            return self._java_primitive(type_node.element_type.name) + "[]"
        if isinstance(type_node, ReferenceType):
            return type_node.name
        raise RuntimeError(f"Unknown type in Java type mapping: {type_node}")

    def _java_default(self, type_node, enum_names: Set[str]) -> str:
        if isinstance(type_node, PrimitiveType):
            return {
                "i8":          "(byte) 0",
                "char":        "(byte) 0",
                "i16":         "(short) 0",
                "i32":         "0",
                "i64":         "0L",
                "datetime_ns": "0L",
                "bool":        "false",
            }[type_node.name]
        if isinstance(type_node, StringType):
            return '""'
        if isinstance(type_node, BytesType):
            return "new byte[0]"
        if isinstance(type_node, ArrayType):
            java_elem = self._java_primitive(type_node.element_type.name)
            return f"new {java_elem}[{type_node.length}]"
        if isinstance(type_node, ListType):
            elem_type_str = self._java_type(type_node.element_type, enum_names)
            return self._java_new_array(elem_type_str, "0")
        if isinstance(type_node, ReferenceType):
            return "null"
        raise RuntimeError(f"No Java default for type: {type_node}")

    def _java_new_array(self, element_type_str: str, count_expr: str) -> str:
        """Build a Java array allocation expression for potentially multi-dimensional arrays.

        _java_new_array("int",    "n") -> "new int[n]"
        _java_new_array("int[]",  "n") -> "new int[n][]"
        _java_new_array("int[][]","n") -> "new int[n][][]"
        """
        base = element_type_str
        suffix = ""
        while base.endswith("[]"):
            suffix += "[]"
            base = base[:-2]
        return f"new {base}[{count_expr}]{suffix}"

    # ------------------------------------------------------------------
    # Wire-format helpers
    # ------------------------------------------------------------------

    def _primitive_wire_size(self, name: str) -> int:
        return {
            "i8":          1,
            "char":        1,
            "bool":        1,
            "i16":         2,
            "i32":         4,
            "i64":         8,
            "datetime_ns": 8,
        }[name]

    def _emit_buf_put(self, prim_name: str, expr: str) -> str:
        if prim_name in ("i8", "char"):
            return f"buf.put({expr})"
        if prim_name == "bool":
            return f"buf.put({expr} ? (byte) 1 : (byte) 0)"
        if prim_name == "i16":
            return f"buf.putShort({expr})"
        if prim_name == "i32":
            return f"buf.putInt({expr})"
        if prim_name in ("i64", "datetime_ns"):
            return f"buf.putLong({expr})"
        raise RuntimeError(f"Unknown primitive in buf put: {prim_name}")

    def _emit_buf_get(self, prim_name: str) -> str:
        if prim_name in ("i8", "char"):
            return "buf.get()"
        if prim_name == "bool":
            return "(buf.get() != 0)"
        if prim_name == "i16":
            return "buf.getShort()"
        if prim_name == "i32":
            return "buf.getInt()"
        if prim_name in ("i64", "datetime_ns"):
            return "buf.getLong()"
        raise RuntimeError(f"Unknown primitive in buf get: {prim_name}")

    def _emit_buf_put_enum(self, underlying_type: str, expr: str) -> str:
        if underlying_type in ("i8", "char"):
            return f"buf.put((byte) {expr}.value)"
        if underlying_type == "i16":
            return f"buf.putShort((short) {expr}.value)"
        if underlying_type == "i32":
            return f"buf.putInt((int) {expr}.value)"
        if underlying_type == "i64":
            return f"buf.putLong({expr}.value)"
        raise RuntimeError(f"Unknown enum underlying type: {underlying_type}")

    def _emit_buf_get_enum(self, underlying_type: str) -> str:
        if underlying_type in ("i8", "char"):
            return "buf.get()"
        if underlying_type == "i16":
            return "buf.getShort()"
        if underlying_type == "i32":
            return "buf.getInt()"
        if underlying_type == "i64":
            return "buf.getLong()"
        raise RuntimeError(f"Unknown enum underlying type: {underlying_type}")
