#pragma once

// Copyright (c) 2024-2026 Andrew Peter Marlow. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#include <quill/LogMacros.h>

#include <fmt/format.h>

#include <pubsub_itc_fw/FwLogLevel.hpp>
#include <pubsub_itc_fw/QuillLogger.hpp>

/** @ingroup logging_subsystem */

// =============================================================================
// Format string safety
// =============================================================================
//
// The fmt argument to PUBSUB_LOG must always be a string literal, for example:
//
//   PUBSUB_LOG(logger, FwLogLevel::Info, "connected to {} on port {}", host, port);
//
// NEVER pass a runtime string or a variable as the fmt argument.
//
// Runtime detection: if a format string does not match its argument list, the
// Quill backend catches the error inside its formatting path and emits a normal
// log record containing:
//   [Could not format log statement. message: "...", location: "...", error: "..."]
// This record appears in the applog file and any other configured sinks, so it
// will be visible during testing. Note: the BackendOptions::error_notifier
// callback is NOT invoked for format errors in Quill 11.0.2 -- it is only used
// for queue failures and backend exceptions.
//
// =============================================================================

namespace pubsub_itc_fw::logging_help {

/***
 * @brief Forces compile-time validation of the format string and its arguments.
 * * This helper is a critical safety mechanism for C++17 environments. While C++20
 * provides 'consteval' for immediate function evaluation, C++17 requires a
 * template-based approach to trigger build failures on format mismatches.
 * * @section why_this_works The Mechanics of the Fix:
 * 1. The macro passes a unique type generated by FMT_STRING(fmt) as the 'S' parameter.
 * 2. By instantiating fmt::format<S, Args...>, we force the compiler to perform
 * semantic analysis of the format string against the argument types.
 * 3. If a mismatch is detected (e.g., "{}" with no arguments), the fmt library
 * triggers a static_assert, halting the build.
 * * @note This function is wrapped in an 'if (false)' block within the PUBSUB_LOG macro.
 * This ensures the compiler validates the logic during the semantic analysis phase,
 * but the optimiser completely elides the call, resulting in zero runtime overhead.
 *
 * * @tparam S The unique type representing the format string literal.
 * @tparam Args The types of the arguments to be formatted.
 * @param format_str The format string literal wrapped by FMT_STRING.
 * @param args The arguments to validate.
 */
template <typename S, typename... Args> void validate_at_compile_time(S format_str, const Args&... args) {
    // This instantiation forces the compiler to parse the format string
    // type against the provided argument types.
    (void)fmt::format(format_str, args...);
}

} // namespace pubsub_itc_fw::logging_help

// In clang-tidy analysis mode the macros are neutralised to avoid false
// positives from the variadic forwarding.
#ifdef CLANG_TIDY
// NOLINTNEXTLINE(cppcoreguidelines-macro-usage)
#define PUBSUB_LOG(logger_expr, log_level_expr, fmt, ...)                                                                                                      \
    do {                                                                                                                                                       \
    } while (0)
// NOLINTNEXTLINE(cppcoreguidelines-macro-usage)
#define PUBSUB_LOG_STR(logger_expr, log_level_expr, msg)                                                                                                       \
    do {                                                                                                                                                       \
    } while (0)
#else

// PUBSUB_LOG — log a format string with zero or more arguments.
//
// Arguments are serialised into Quill's lock-free ring buffer on the calling
// thread and formatted on the Quill backend thread.  No string construction
// occurs here.
//
// Usage:
//   PUBSUB_LOG(logger, FwLogLevel::Info, "connected to {} port {}", host, port);
#define PUBSUB_LOG(logger_expr, log_level_expr, fmt, ...)                                                                                                      \
    do {                                                                                                                                                       \
        auto& pubsub_logger = (logger_expr);                                                                                                                   \
        const ::pubsub_itc_fw::FwLogLevel pubsub_level = (log_level_expr);                                                                                     \
        if (false) {                                                                                                                                           \
            ::pubsub_itc_fw::logging_help::validate_at_compile_time(FMT_STRING(fmt), ##__VA_ARGS__);                                                           \
        }                                                                                                                                                      \
        if (pubsub_level == ::pubsub_itc_fw::FwLogLevel::Alert || pubsub_level == ::pubsub_itc_fw::FwLogLevel::Critical) {                                     \
            LOG_CRITICAL(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                    \
        } else if (pubsub_level == ::pubsub_itc_fw::FwLogLevel::Error) {                                                                                       \
            LOG_ERROR(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                       \
        } else if (pubsub_level == ::pubsub_itc_fw::FwLogLevel::Warning) {                                                                                     \
            LOG_WARNING(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                     \
        } else if (pubsub_level == ::pubsub_itc_fw::FwLogLevel::Notice || pubsub_level == ::pubsub_itc_fw::FwLogLevel::Info) {                                 \
            LOG_INFO(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                        \
        } else if (pubsub_level == ::pubsub_itc_fw::FwLogLevel::Debug) {                                                                                       \
            LOG_DEBUG(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                       \
        } else {                                                                                                                                               \
            LOG_TRACE_L3(pubsub_logger.quill_logger(), fmt, ##__VA_ARGS__);                                                                                    \
        }                                                                                                                                                      \
    } while (0)

// PUBSUB_LOG_STR — log a single pre-formed string.
//
// Equivalent to PUBSUB_LOG with "{}" as the format string.  Required because
// -Werror=variadic-macros rejects a macro invocation with no variadic args.
//
// Usage:
//   PUBSUB_LOG_STR(logger, FwLogLevel::Warning, some_std_string);
#define PUBSUB_LOG_STR(logger_expr, log_level_expr, msg) PUBSUB_LOG(logger_expr, log_level_expr, "{}", msg)

#endif // CLANG_TIDY
