#pragma once

// Copyright (c) 2024-2026 Andrew Peter Marlow. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#include <sstream>   // For std::ostringstream
#include <stdexcept> // For std::logic_error
#include <string>    // For std::string
#include <utility>   // For std::move

#include <cpptrace/basic.hpp> // For cpptrace::stacktrace and cpptrace::generate_trace

// For this specific file, we will directly include the StringUtils (if leafname is moved there)
// or just use filename directly if leafname is not part of this core framework.
// For now, let's assume `Utils::leafname` is external or will be integrated.
// If it's not a common utility, it might be simplified or adapted.

namespace pubsub_itc_fw {

namespace {

std::string get_leafname(const char* filepath) {
    std::string path_str(filepath);
    const size_t pos = path_str.find_last_of("/\\");
    if (pos == std::string::npos) {
        return path_str;
    }
    return path_str.substr(pos + 1);
}
} // namespaces

/** @ingroup utilities_subsystem */

/**
 * @brief Exception class for representing a precondition assertion failure.
 *
 * This class derives from `std::logic_error` and is used to signal situations
 * where a function's precondition has been violated. It provides detailed
 * context including a message, filename, and line number where the assertion
 * was thrown, assisting in debugging.
 *
 * The message is followed by the stack as it stood where the assertion was
 * raised. The trace is taken in the constructor, which runs immediately before
 * the throw expression completes, so the frames that say how the process
 * reached the assertion are still on the stack. This is the whole reason for
 * capturing here rather than at the catch: by the time an exception reaches a
 * handler -- the reactor's event loop, say -- those frames have been unwound
 * and nothing is left but the file and line of the throw itself. A clean
 * termination through this exception was, until now, harder to diagnose than a
 * signal, which at least leaves a symbolised stack in the journal.
 *
 * The trace is also kept whole, reachable through stack_trace(), for a caller
 * that wants the frames rather than the rendering.
 */
class PreconditionAssertion : public std::logic_error {
  public:
    /**
     * @brief Constructs a PreconditionAssertion with a message, filename, and line number.
     * @param message The detailed error message.
     * @param filename The name of the file where the assertion was triggered.
     * @param line_number The line number in the file where the assertion was triggered.
     */
    PreconditionAssertion(const std::string& message, const char* filename, int line_number)
        : PreconditionAssertion(message, filename, line_number, cpptrace::generate_trace(1)) {}

    /**
     * @brief Constructs a PreconditionAssertion with a C-style string message, filename, and line number.
     * @param message The detailed error message as a C-style string.
     * @param filename The name of the file where the assertion was triggered.
     * @param line_number The line number in the file where the assertion was triggered.
     */
    PreconditionAssertion(const char* message, const char* filename, int line_number)
        : PreconditionAssertion(std::string(message), filename, line_number, cpptrace::generate_trace(1)) {}

    /**
     * @brief The stack as it stood where the assertion was raised.
     * @return The captured trace, whose first frame is the function that threw.
     */
    const cpptrace::stacktrace& stack_trace() const {
        return stack_trace_;
    }

  private:
    /**
     * @brief Delegated-to constructor, taking the trace the public constructors captured.
     *
     * The trace is generated by the public constructor rather than here, so that the frame
     * skipped is the one belonging to the constructor the throwing code named, and so that it
     * is generated once: the base class is built from it and this object then takes ownership.
     * @param message The detailed error message.
     * @param filename The name of the file where the assertion was triggered.
     * @param line_number The line number in the file where the assertion was triggered.
     * @param trace The stack captured at the point the assertion was raised.
     */
    PreconditionAssertion(const std::string& message, const char* filename, int line_number, cpptrace::stacktrace trace)
        : std::logic_error(assemble_assertion_message(message, filename, line_number, trace)), stack_trace_(std::move(trace)) {}

    /**
     * @brief Helper function to assemble the full assertion message string.
     * @param message The detailed error message.
     * @param filename The name of the file where the assertion was triggered.
     * @param line_number The line number in the file where the assertion was triggered.
     * @param trace The stack captured at the point the assertion was raised.
     * @return The formatted assertion message, followed by the stack trace on the lines after it.
     */
    static std::string assemble_assertion_message(const std::string& message, const char* filename, int line_number, const cpptrace::stacktrace& trace) {
        std::ostringstream output_stream;
        output_stream << message << " (thrown from " << get_leafname(filename) << ":" << line_number << ")";
        // to_string() renders its own "Stack trace (most recent call first):" heading, so the
        // trace explains itself wherever the message is written, with no help from the reader.
        output_stream << "\n" << trace.to_string();
        return output_stream.str();
    }

    /// The stack as it stood where the assertion was raised.
    cpptrace::stacktrace stack_trace_;
};

} // namespaces
