[network]
listen_host = "${arbiter_secondary_network_listen_host}"
listen_port = 7201

[ha]
instance_id = 2

[peer]
listen_host                      = "${arbiter_secondary_peer_listen_host}"
listen_port                      = 7204
host                             = "${arbiter_secondary_peer_host}"
port                             = 7203
fence_file_path                  = "${arbiter_secondary_peer_fence_file_path}"
heartbeat_interval_seconds       = 2
heartbeat_timeout_seconds        = 6
startup_election_timeout_seconds = 20

[witness]
host                       = "${arbiter_secondary_witness_host}"
port                       = 7100
vote_timeout_seconds       = 3
heartbeat_interval_seconds = 30

[logging]
applog_level = "info"
syslog_level = "critical"

[reactor]
cpu_pinning_enabled    = true
cpu_pinning_reserve_cpu0   = ${shared_reactor_cpu_pinning_reserve_cpu0}
cpu_registry_lock_file = "${shared_reactor_cpu_registry_lock_file}"

[event_queue_pool]
objects_per_slab = 64
initial_slabs    = 1

[command_queue_pool]
objects_per_slab = 64
initial_slabs    = 1
