[network]
listen_host = "127.0.0.1"
listen_port = 7201

[ha]
instance_id = 2

[peer]
listen_host                      = "127.0.0.1"
listen_port                      = 7204
host                             = "127.0.0.1"
port                             = 7203
fence_file_path                  = "/dev/shm/arbiter_secondary_fence"
heartbeat_interval_seconds       = 5
heartbeat_timeout_seconds        = 15
startup_election_timeout_seconds = 20

[witness]
host                       = "127.0.0.1"
port                       = 7100
vote_timeout_seconds       = 3
heartbeat_interval_seconds = 30

[logging]
applog_level = "info"
syslog_level = "critical"

[reactor]
cpu_pinning_enabled    = true
cpu_pinning_dev_mode   = true
cpu_registry_lock_file = "/dev/shm/pubsub_cpu_registry.lock"

[event_queue_pool]
objects_per_slab = 64
initial_slabs    = 1

[command_queue_pool]
objects_per_slab = 64
initial_slabs    = 1
