#!/usr/bin/env python3
"""
export_credentials.py — Export SCRAM credentials from the database to the
authentication service credentials.toml file.

Reads all enabled, unlocked comp_ids (whose firm is also enabled) from the
database and writes them as [[credential]] TOML entries to the credentials
file that the authentication service reads at startup.

Disabled comp_ids, locked comp_ids, and comp_ids belonging to a disabled firm
are silently excluded.  The auth service will return Denied for any comp_id not
present in the file.

Run this script after making credential changes via the Java admin service and
before (re)starting the authentication service.  Live credential updates while
the service is already running go via SetCredentialRequest (PDU 510) and do not
require a restart.

Usage:
    python3 db/export_credentials.py [options]

Environment:
    PUBSUB_APP_DB_PASSWORD   Password for the pubsub_app database role.
                             Falls back to 'pubsub_dev' if not set.
"""

import argparse
import csv
import io
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_DB_NAME      = "pubsub"
DEFAULT_DB_HOST      = "localhost"
DEFAULT_DB_PORT      = 5432
DEFAULT_DB_USER      = "pubsub_app"
DEFAULT_APP_PASS_ENV = "PUBSUB_APP_DB_PASSWORD"
DEFAULT_DEV_PASSWORD = "pubsub_dev"
DEFAULT_TABLE_PREFIX = "pubsub_"

_SCRIPT_DIR    = Path(__file__).resolve().parent
_PROJECT_ROOT  = _SCRIPT_DIR.parent
_DEFAULT_CREDS = (
    _PROJECT_ROOT / "applications" / "authentication_service" / "credentials.toml"
)


def _query_credentials(host: str, port: int, username: str, password: str,
                        db_name: str, table_prefix: str) -> list[dict]:
    firm_table    = f"{table_prefix}firm"
    comp_id_table = f"{table_prefix}comp_id"
    sql = (
        f"SELECT ci.comp_id, ci.stored_key, ci.server_key, ci.salt, ci.iterations "
        f"FROM {comp_id_table} ci "
        f"JOIN {firm_table} f ON ci.firm_id = f.firm_id "
        f"WHERE ci.enabled = true "
        f"  AND f.enabled  = true "
        f"  AND ci.locked  = false "
        f"ORDER BY ci.comp_id;"
    )
    env = {**os.environ, "PGPASSWORD": password}
    result = subprocess.run(
        ["psql",
         "--host", host, "--port", str(port),
         "--username", username, "--dbname", db_name,
         "--csv", "--tuples-only",
         "--command", sql],
        capture_output=True, text=True, check=True, env=env,
    )
    reader = csv.DictReader(
        io.StringIO(result.stdout),
        fieldnames=["comp_id", "stored_key", "server_key", "salt", "iterations"],
    )
    return list(reader)


def _write_credentials_toml(path: Path, rows: list[dict]) -> None:
    lines = [
        "# SCRAM-SHA-256 credentials for the authentication service.\n",
        "#\n",
        "# Generated by db/export_credentials.py — do not edit by hand.\n",
        "# Re-run whenever credentials change in the database.\n",
        "#\n",
        "#   comp_id    -- identity string sent in AuthenticationRequest\n",
        "#   stored_key -- hex SHA-256(HMAC-SHA-256(SaltedPassword, \"Client Key\"))\n",
        "#   server_key -- hex HMAC-SHA-256(SaltedPassword, \"Server Key\")\n",
        "#   salt       -- hex random salt used during PBKDF2 derivation\n",
        "#   iterations -- PBKDF2 iteration count\n",
        "\n",
    ]
    for row in rows:
        lines.append("[[credential]]\n")
        lines.append(f'comp_id    = "{row["comp_id"]}"\n')
        lines.append(f'stored_key = "{row["stored_key"]}"\n')
        lines.append(f'server_key = "{row["server_key"]}"\n')
        lines.append(f'salt       = "{row["salt"]}"\n')
        lines.append(f'iterations = {row["iterations"]}\n')
        lines.append("\n")

    # Atomic write: temp file then rename so the auth service never sees
    # a partial file if it re-reads credentials.
    tmp = path.with_suffix(".tmp")
    tmp.write_text("".join(lines), encoding="utf-8")
    tmp.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--credentials-file", type=Path, default=_DEFAULT_CREDS,
        metavar="PATH",
        help=f"credentials.toml to write (default: {_DEFAULT_CREDS})",
    )
    parser.add_argument(
        "--db-host", default=DEFAULT_DB_HOST,
        help=f"PostgreSQL host (default: {DEFAULT_DB_HOST})",
    )
    parser.add_argument(
        "--db-port", type=int, default=DEFAULT_DB_PORT,
        help=f"PostgreSQL port (default: {DEFAULT_DB_PORT})",
    )
    parser.add_argument(
        "--db-name", default=DEFAULT_DB_NAME,
        help=f"Database name (default: {DEFAULT_DB_NAME})",
    )
    parser.add_argument(
        "--db-user", default=DEFAULT_DB_USER,
        help=f"Database role to connect as (default: {DEFAULT_DB_USER})",
    )
    parser.add_argument(
        "--table-prefix", default=DEFAULT_TABLE_PREFIX,
        help=f"Table prefix (default: {DEFAULT_TABLE_PREFIX})",
    )
    args = parser.parse_args()

    password = os.environ.get(DEFAULT_APP_PASS_ENV, DEFAULT_DEV_PASSWORD)

    print("=== export credentials ===")
    print(f"  source  : {args.db_host}:{args.db_port}/{args.db_name}"
          f"  (user: {args.db_user})")
    print(f"  password: from {DEFAULT_APP_PASS_ENV}" + (
        "" if DEFAULT_APP_PASS_ENV in os.environ else " (not set — using dev default)"))
    print(f"  output  : {args.credentials_file}")
    print()

    print("--- Querying database ---")
    rows = _query_credentials(
        args.db_host, args.db_port, args.db_user, password,
        args.db_name, args.table_prefix,
    )
    print(f"  found {len(rows)} active credential(s)")
    for row in rows:
        print(f"    {row['comp_id']}")
    print()

    if not rows:
        print("warning: no credentials to export — output file will contain no entries",
              file=sys.stderr)

    print("--- Writing credentials file ---")
    _write_credentials_toml(args.credentials_file, rows)
    print(f"  written: {args.credentials_file}")
    print()
    print("=== Done ===")


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"\nerror: command failed with exit code {exc.returncode}", file=sys.stderr)
        if exc.stderr:
            print(exc.stderr, file=sys.stderr)
        sys.exit(exc.returncode)
