"""Tests for the `topic` grouping construct and the topic registry/catalog generators."""

import pytest

from dsl.lexer import Lexer
from dsl.parser import Parser
from dsl.validator import Validator
from dsl.errors import ParseError, ValidationError
from dsl.ast import TopicDecl
from dsl.generator_topics import TopicsGenerator


BASE_MESSAGES = """
message NewOrderSingle (id=1000)
    i64 price
end

message OrderCancelRequest (id=1001)
    i64 order_id
end

message ExecutionReport (id=1002)
    i64 exec_id
end
"""


def _parse(text):
    return Parser(text).parse()


def _validate(text):
    ast = _parse(text)
    Validator(ast).validate()
    return ast


# -----------------------------------------------------------------------------
# Lexer / parser
# -----------------------------------------------------------------------------

def test_topic_is_a_keyword():
    lexer = Lexer("topic")
    tok = lexer.next_token()
    assert tok.kind == "KEYWORD" and tok.value == "topic"


def test_parser_yields_topic_decl():
    ast = _parse(BASE_MESSAGES + """
        topic orders {
            NewOrderSingle,
            OrderCancelRequest
        }
    """)
    topics = [d for d in ast.declarations if isinstance(d, TopicDecl)]
    assert len(topics) == 1
    assert topics[0].name == "orders"
    assert topics[0].members == ["NewOrderSingle", "OrderCancelRequest"]


def test_parser_tolerates_trailing_comma():
    ast = _parse(BASE_MESSAGES + "topic orders { NewOrderSingle, }")
    topic = next(d for d in ast.declarations if isinstance(d, TopicDecl))
    assert topic.members == ["NewOrderSingle"]


def test_parser_rejects_empty_topic():
    with pytest.raises(ParseError, match="has no members"):
        _parse("topic empty { }")


# -----------------------------------------------------------------------------
# Validator
# -----------------------------------------------------------------------------

def test_valid_topic_passes():
    ast = _validate(BASE_MESSAGES + "topic orders { NewOrderSingle, OrderCancelRequest }")
    assert any(isinstance(d, TopicDecl) for d in ast.declarations)


def test_message_may_belong_to_multiple_topics():
    _validate(BASE_MESSAGES + """
        topic orders { NewOrderSingle, OrderCancelRequest }
        topic all_orders { NewOrderSingle, OrderCancelRequest, ExecutionReport }
    """)


def test_unknown_member_is_rejected():
    with pytest.raises(ValidationError, match="unknown message 'Nope'"):
        _validate(BASE_MESSAGES + "topic orders { NewOrderSingle, Nope }")


def test_duplicate_topic_name_is_rejected():
    with pytest.raises(ValidationError, match="duplicate topic name 'orders'"):
        _validate(BASE_MESSAGES + """
            topic orders { NewOrderSingle }
            topic orders { OrderCancelRequest }
        """)


def test_duplicate_member_within_topic_is_rejected():
    with pytest.raises(ValidationError, match="more than once"):
        _validate(BASE_MESSAGES + "topic orders { NewOrderSingle, NewOrderSingle }")


def test_enum_member_is_rejected():
    with pytest.raises(ValidationError, match="is an enum, not a message"):
        _validate("""
            enum Colour : i16 { Red = 1 }
            topic t { Colour }
        """)


# -----------------------------------------------------------------------------
# Registry generator
# -----------------------------------------------------------------------------

TWO_TOPICS = BASE_MESSAGES + """
topic orders { NewOrderSingle, OrderCancelRequest }
topic execution_reports { ExecutionReport }
"""


def _registry(text):
    ast = _validate(text)
    return TopicsGenerator(namespace="pubsub_itc_fw_app").emit_registry(ast, "test.dsl")


def test_registry_has_banner_and_guard():
    code = _registry(TWO_TOPICS)
    assert "Do NOT edit this file manually." in code
    assert "Source:       test.dsl" in code
    assert "#pragma once" in code
    assert "namespace pubsub_itc_fw_app {" in code


def test_registry_emits_topic_enum():
    code = _registry(TWO_TOPICS)
    assert "enum class Topic : std::uint16_t {" in code
    assert "orders = 0," in code
    assert "execution_reports = 1," in code
    assert "inline constexpr std::size_t topic_count = 2;" in code


def test_registry_emits_to_string_and_name_lookup():
    code = _registry(TWO_TOPICS)
    assert 'case Topic::orders: return std::string_view("orders");' in code
    assert 'if (name == std::string_view("orders")) { out = Topic::orders; return true; }' in code


def test_registry_emits_membership_table_with_resolved_ids():
    code = _registry(TWO_TOPICS)
    assert "std::array<TopicMember, 3> topic_members" in code
    assert "TopicMember{1000, Topic::orders}," in code
    assert "TopicMember{1001, Topic::orders}," in code
    assert "TopicMember{1002, Topic::execution_reports}," in code


def test_registry_emits_pdu_in_topic_predicate():
    code = _registry(TWO_TOPICS)
    assert "inline constexpr bool pdu_in_topic(std::int64_t pdu_id, Topic topic) {" in code


def test_registry_reflects_multi_membership():
    # NewOrderSingle appears in both topics -> two rows for pdu 1000.
    code = _registry(BASE_MESSAGES + """
        topic orders { NewOrderSingle }
        topic everything { NewOrderSingle, ExecutionReport }
    """)
    assert code.count("TopicMember{1000,") == 2


# -----------------------------------------------------------------------------
# Catalog generator
# -----------------------------------------------------------------------------

def _catalog(text):
    ast = _validate(text)
    return TopicsGenerator(namespace="pubsub_itc_fw_app").emit_catalog(ast, "test.dsl")


def test_catalog_has_banner_and_tables():
    md = _catalog(TWO_TOPICS)
    assert md.startswith("<!--")
    assert "Do NOT edit this file manually." in md
    assert "# Topic catalog" in md
    assert "## `orders` (Topic = 0)" in md
    assert "## `execution_reports` (Topic = 1)" in md
    assert "| `NewOrderSingle` | 1000 |" in md
    assert "| `ExecutionReport` | 1002 |" in md
