"""Emit a zero-copy-friendly C++17 header from a merged FIX dictionary."""

from __future__ import annotations

from typing import Callable, Dict, List

from .model import Dictionary, FieldDef

Writer = Callable[[str], None]


def emit_header(dictionary: Dictionary, namespace: str) -> str:
    """Return the complete generated C++ header as a single string."""
    lines: List[str] = []
    write = lines.append

    _emit_preamble(write)
    write(f"namespace {namespace} {{")
    write("")
    _emit_tags(write, dictionary)
    _emit_message_types(write, dictionary)
    _emit_enum_values(write, dictionary)
    _emit_lookup_tables(write, dictionary)
    _emit_lookup_functions(write)
    write(f"}}  // namespace {namespace}")
    write("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def _emit_preamble(write: Writer) -> None:
    """Emit the do-not-edit banner, include guard, and system includes."""
    write("// -----------------------------------------------------------------------------")
    write("//  This file was automatically generated by the FIX dictionary generator")
    write("//  (python/tools/generate_fix_dictionary.py). Do NOT edit this file manually;")
    write("//  regenerate it from the FIX XML data dictionary instead.")
    write("// -----------------------------------------------------------------------------")
    write("")
    write("#pragma once")
    write("")
    write("#include <array>")
    write("#include <cstddef>")
    write("#include <string_view>")
    write("#include <utility>")
    write("")


def _emit_tags(write: Writer, dictionary: Dictionary) -> None:
    """Emit ``namespace tag`` with one ``int`` constant per field number."""
    write("// Tag numbers, keyed by canonical FIX field name.")
    write("namespace tag {")
    used: Dict[str, bool] = {}
    for field_def in dictionary.fields_sorted():
        identifier = _disambiguate(_sanitize(field_def.name), used, str(field_def.number))
        write(f"inline constexpr int {identifier} = {field_def.number};")
    write("}  // namespace tag")
    write("")


def _emit_message_types(write: Writer, dictionary: Dictionary) -> None:
    """Emit ``namespace msg_type`` with a ``string_view`` per message type."""
    write("// Message-type (tag 35) values, keyed by canonical FIX message name.")
    write("namespace msg_type {")
    used: Dict[str, bool] = {}
    for message in dictionary.messages_sorted():
        identifier = _disambiguate(_sanitize(message.name), used, _sanitize(message.msgtype))
        write(f"inline constexpr std::string_view {identifier} = {_string_literal(message.msgtype)};")
    write("}  // namespace msg_type")
    write("")


def _emit_enum_values(write: Writer, dictionary: Dictionary) -> None:
    """Emit ``namespace enum_values`` with a nested namespace per enum field."""
    fields_with_values = [field_def for field_def in dictionary.fields_sorted() if field_def.values]
    if not fields_with_values:
        return
    write("// Enumerated field values, grouped by field name.")
    write("namespace enum_values {")
    used_namespaces: Dict[str, bool] = {}
    for field_def in fields_with_values:
        _emit_field_values(write, field_def, used_namespaces)
    write("}  // namespace enum_values")
    write("")


def _emit_field_values(write: Writer, field_def: FieldDef, used_namespaces: Dict[str, bool]) -> None:
    """Emit one nested namespace of constants for a single enumerated field."""
    namespace = _disambiguate(_sanitize(field_def.name), used_namespaces, str(field_def.number))
    single_char = all(len(value.enum) == 1 for value in field_def.values)
    write(f"namespace {namespace} {{")
    used: Dict[str, bool] = {}
    for index, value in enumerate(field_def.values):
        base = _sanitize(value.description) or ("ENUM_" + _sanitize(value.enum))
        identifier = _disambiguate(base, used, str(index))
        if single_char:
            write(f"inline constexpr char {identifier} = {_char_literal(value.enum)};")
        else:
            write(f"inline constexpr std::string_view {identifier} = {_string_literal(value.enum)};")
    write(f"}}  // namespace {namespace}")


def _emit_lookup_tables(write: Writer, dictionary: Dictionary) -> None:
    """Emit the sorted tag->name and length->data lookup tables."""
    fields = dictionary.fields_sorted()
    pairs = dictionary.data_length_pairs()
    write("namespace detail {")
    write(f"inline constexpr std::array<std::pair<int, std::string_view>, {len(fields)}> field_name_table = {{{{")
    for field_def in fields:
        write(f"    {{{field_def.number}, {_string_literal(field_def.name)}}},")
    write("}};")
    write("")
    _emit_pair_table(write, pairs)
    write("}  // namespace detail")
    write("")


def _emit_pair_table(write: Writer, pairs: List) -> None:
    """Emit the ``data_length_pairs`` table (handling the empty case)."""
    if not pairs:
        write("inline constexpr std::array<std::pair<int, int>, 0> data_length_pairs = {};")
        return
    write(f"inline constexpr std::array<std::pair<int, int>, {len(pairs)}> data_length_pairs = {{{{")
    for length_tag, data_tag in pairs:
        write(f"    {{{length_tag}, {data_tag}}},")
    write("}};")


def _emit_lookup_functions(write: Writer) -> None:
    """Emit the constexpr binary-search accessors over the lookup tables."""
    write("// Returns the canonical field name for a tag, or an empty view if unknown.")
    write("inline constexpr std::string_view tag_name(int field_tag) {")
    write("    size_t low = 0;")
    write("    size_t high = detail::field_name_table.size();")
    write("    while (low < high) {")
    write("        const size_t mid = low + (high - low) / 2;")
    write("        if (detail::field_name_table[mid].first < field_tag) {")
    write("            low = mid + 1;")
    write("        } else {")
    write("            high = mid;")
    write("        }")
    write("    }")
    write("    if (low < detail::field_name_table.size() && detail::field_name_table[low].first == field_tag) {")
    write("        return detail::field_name_table[low].second;")
    write("    }")
    write("    return {};")
    write("}")
    write("")
    write("// Returns the data field paired with a LENGTH tag, or 0 if the tag is not a data-length tag.")
    write("inline constexpr int data_field_for_length_tag(int length_tag) {")
    write("    size_t low = 0;")
    write("    size_t high = detail::data_length_pairs.size();")
    write("    while (low < high) {")
    write("        const size_t mid = low + (high - low) / 2;")
    write("        if (detail::data_length_pairs[mid].first < length_tag) {")
    write("            low = mid + 1;")
    write("        } else {")
    write("            high = mid;")
    write("        }")
    write("    }")
    write("    if (low < detail::data_length_pairs.size() && detail::data_length_pairs[low].first == length_tag) {")
    write("        return detail::data_length_pairs[low].second;")
    write("    }")
    write("    return 0;")
    write("}")
    write("")
    write("// True when a tag is a LENGTH field that precedes a binary DATA field.")
    write("inline constexpr bool is_data_length_tag(int length_tag) {")
    write("    return data_field_for_length_tag(length_tag) != 0;")
    write("}")
    write("")


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _sanitize(name: str) -> str:
    """Turn an arbitrary dictionary string into a valid C++ identifier."""
    result = "".join(character if (character.isalnum() or character == "_") else "_" for character in name)
    if result and result[0].isdigit():
        result = "_" + result
    return result


def _disambiguate(identifier: str, used: Dict[str, bool], suffix: str) -> str:
    """Return ``identifier``, or a suffixed variant if it is already taken."""
    if identifier not in used:
        used[identifier] = True
        return identifier
    candidate = f"{identifier}_{suffix}"
    while candidate in used:
        candidate = f"{candidate}_"
    used[candidate] = True
    return candidate


def _char_literal(value: str) -> str:
    """Render a single character as a C++ char literal."""
    if value == "\\":
        return "'\\\\'"
    if value == "'":
        return "'\\''"
    return f"'{value}'"


def _string_literal(value: str) -> str:
    """Render a string as a C++ string literal with escaping."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
