credentials_file = "credentials.toml"

[network]
listen_host = "${auth_service_secondary_network_listen_host}"
listen_port = ${auth_service_secondary_network_listen_port}

[admin]
listen_port                    = ${auth_service_secondary_admin_listen_port}
tls_certificate_path           = "admin.crt"
tls_private_key_path           = "admin.key"
tls_ca_path                    = ""
tls_require_client_certificate = false

[logging]
applog_level     = "info"
syslog_level     = "critical"
mode             = "none"
max_file_size    = 10240000
max_backup_files = 10

[reactor]
cpu_pinning_enabled    = false
cpu_pinning_reserve_cpu0   = ${shared_reactor_cpu_pinning_reserve_cpu0}
cpu_registry_lock_file = "${shared_reactor_cpu_registry_lock_file}"
connect_retry_warning_interval = "15m"

[event_queue_pool]
objects_per_slab = 64
initial_slabs    = 1

[command_queue_pool]
objects_per_slab = 64
initial_slabs    = 1
